import React from "react";
import {AbsoluteFill,Audio,Img,interpolate,OffthreadVideo,Sequence,useCurrentFrame} from "remotion";
import type {CSSProperties} from "react";
import {DEFAULT_MOTION_TRANSFORM,type Clip,type MotionTransform} from "../schemas/clip";
import type {Asset} from "../schemas/asset";
import type {Project} from "../schemas/project";
import {EFFECTS_BY_ID} from "../shared/effects/registry";
import {CaptionOverlay} from "../components/captions/CaptionOverlay";
import {resolveMotionStyle} from "../lib/styles/resolve";

export type MasterCompositionProps={project:Project;assetUrls?:Record<string,string>;renderMode?:"preview"|"final"|"overlay"};
type VideoClip=Extract<Clip,{type:"video"}>;type MotionClip=Extract<Clip,{type:"motion"}>;type CaptionClip=Extract<Clip,{type:"caption"}>;type BrollClip=Extract<Clip,{type:"broll"}>;type AudioClip=Extract<Clip,{type:"audio"}>;type VisualClip=VideoClip|MotionClip|CaptionClip|BrollClip;
const anchorOrigins:Record<MotionTransform["anchor"],string>={"top-left":"0% 0%",top:"50% 0%","top-right":"100% 0%",left:"0% 50%",center:"50% 50%",right:"100% 50%","bottom-left":"0% 100%",bottom:"50% 100%","bottom-right":"100% 100%"};const typeRank:Record<VisualClip["type"],number>={video:0,broll:1,motion:2,caption:3};
const transformCss=(value:MotionTransform)=>`translate3d(${value.x}px, ${value.y}px, 0) scale(${value.scale}) rotate(${value.rotation??0}deg)`;const mediaStyle=(transform:MotionTransform|undefined,fit:"contain"|"cover"="contain"):CSSProperties=>{const value={...DEFAULT_MOTION_TRANSFORM,...(transform??{})};return{width:"100%",height:"100%",objectFit:fit,transform:transformCss(value),transformOrigin:anchorOrigins[value.anchor],opacity:value.opacity};};const fadeGain=(frame:number,duration:number,fadeIn:number,fadeOut:number)=>{const a=fadeIn?interpolate(frame,[0,Math.min(fadeIn,duration)],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}):1;const start=Math.max(0,duration-Math.min(fadeOut,duration));const b=fadeOut?interpolate(frame,[start,duration],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}):1;return Math.min(a,b);};
export const brollMediaKind=(assetKind:Asset["kind"]|undefined):"image"|"video"=>assetKind==="image"?"image":"video";
const BrollLayer=({assetKind,clip,src}:{assetKind:Asset["kind"]|undefined;clip:BrollClip;src:string})=>{const frame=useCurrentFrame();const gain=fadeGain(frame,clip.durationInFrames,clip.fadeInFrames??0,clip.fadeOutFrames??0);const style=mediaStyle(clip.transform,clip.fit??"cover");const renderedStyle={...style,opacity:Number(style.opacity??1)*gain};if(brollMediaKind(assetKind)==="image")return <Img src={src} style={renderedStyle}/>;return <OffthreadVideo src={src} trimBefore={clip.sourceStartFrame??0} volume={clip.muted?0:clip.volume??1} style={renderedStyle}/>;};const AudioLayer=({clip,src}:{clip:AudioClip;src:string})=>{const frame=useCurrentFrame();const gain=fadeGain(frame,clip.durationInFrames,clip.fadeInFrames??0,clip.fadeOutFrames??0);return <Audio src={src} trimBefore={clip.sourceStartFrame} volume={clip.muted?0:clip.volume*gain}/>;};
const MotionLayer=({project,clip,assetUrls}:{project:Project;clip:MotionClip;assetUrls:Record<string,string>})=>{const resolved=resolveMotionStyle(project,clip);const style:CSSProperties={transform:transformCss(resolved.transform),transformOrigin:anchorOrigins[resolved.transform.anchor],opacity:resolved.transform.opacity};if(clip.engine==="hyperframes"){const src=clip.assetId?assetUrls[clip.assetId]:undefined;return src?<AbsoluteFill style={style}><OffthreadVideo src={src} transparent volume={0} style={{width:"100%",height:"100%",objectFit:"contain"}}/></AbsoluteFill>:null;}const effect=EFFECTS_BY_ID[clip.effectId];if(!effect)return null;const parsed=effect.schema.safeParse(resolved.props);if(!parsed.success)return null;const Effect=effect.component;return <AbsoluteFill style={style}><Effect props={parsed.data} motionSpeed={project.brand.motion.speed}/></AbsoluteFill>;};

export const MasterComposition:React.FC<MasterCompositionProps>=({project,assetUrls={},renderMode="preview"})=>{const frame=useCurrentFrame();const overlay=renderMode==="overlay";const clips=project.tracks.filter(track=>!track.hidden).flatMap(track=>track.clips).filter(clip=>clip.enabled);const videos=clips.filter((clip):clip is VideoClip=>clip.type==="video");const audio=clips.filter((clip):clip is AudioClip=>clip.type==="audio");const visuals=clips.filter((clip):clip is VisualClip=>clip.type!=="audio").filter(clip=>!overlay||clip.type==="motion"||clip.type==="caption").sort((a,b)=>a.layer-b.layer||typeRank[a.type]-typeRank[b.type]);
  const renderVisual=(clip:VisualClip)=>{if(clip.type==="video"){const src=assetUrls[clip.assetId];return src?<Sequence key={clip.id} from={clip.startFrame} durationInFrames={clip.durationInFrames}><OffthreadVideo src={src} trimBefore={clip.sourceStartFrame} volume={clip.muted?0:clip.volume} style={mediaStyle(clip.transform,clip.fit??"contain")}/></Sequence>:null;}if(clip.type==="broll"){const src=assetUrls[clip.assetId];const asset=project.assets.find((item)=>item.id===clip.assetId);return src?<Sequence key={clip.id} from={clip.startFrame} durationInFrames={clip.durationInFrames}><BrollLayer assetKind={asset?.kind} clip={clip} src={src}/></Sequence>:null;}if(clip.type==="motion")return <Sequence key={clip.id} from={clip.startFrame} durationInFrames={clip.durationInFrames}><MotionLayer project={project} clip={clip} assetUrls={assetUrls}/></Sequence>;return <Sequence key={clip.id} from={clip.startFrame} durationInFrames={clip.durationInFrames}><AbsoluteFill><CaptionOverlay caption={clip} project={project}/></AbsoluteFill></Sequence>;};
  return <AbsoluteFill style={{backgroundColor:overlay?undefined:project.brand.colors.background,color:project.brand.colors.text,fontFamily:project.brand.typography.bodyFont}}>{visuals.map(renderVisual)}{!overlay&&audio.map(clip=>{const src=assetUrls[clip.assetId];return src?<Sequence key={clip.id} from={clip.startFrame} durationInFrames={clip.durationInFrames}><AudioLayer clip={clip} src={src}/></Sequence>:null;})}{!overlay&&videos.length===0&&renderMode==="preview"?<AbsoluteFill style={{justifyContent:"center",alignItems:"center",padding:80}}><div style={{width:"100%"}}><div style={{color:project.brand.colors.primary,fontSize:34,fontWeight:800,letterSpacing:3}}>VIDEO OS STUDIO</div><div style={{fontSize:76,fontWeight:900,marginTop:28}}>{project.project.name}</div></div></AbsoluteFill>:null}{renderMode==="preview"?<div style={{position:"absolute",right:24,bottom:18,fontSize:20,padding:"8px 12px",borderRadius:8,background:"rgba(0,0,0,.55)",opacity:.72}}>{project.canvas.width}×{project.canvas.height} · {project.canvas.fps} fps · f{frame}</div>:null}</AbsoluteFill>;
};
