"use client";

import {useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent} from "react";
import {snapCanvasTransform,resizeScaleFromPointer,rotationFromPointer,normalizeRotation,type CanvasGuide} from "@/lib/canvas/geometry";
import type {ProjectCommand} from "@/lib/project/commands";
import {DEFAULT_MOTION_TRANSFORM,type Clip,type MotionTransform} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {usePlayerStore} from "@/store/player-store";
import {useSelectionStore} from "@/store/selection-store";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";

type TransformClip=Extract<Clip,{type:"video"|"motion"|"broll"}>;
type Interaction={mode:"drag"|"resize"|"rotate";pointerId:number;clipId:string;startClientX:number;startClientY:number;start:MotionTransform;centerX:number;centerY:number};
type OnCommand=(command:ProjectCommand,message:string)=>Promise<void>;
const isTransformClip=(clip:Clip):clip is TransformClip=>clip.type==="video"||clip.type==="motion"||clip.type==="broll";
const transformFor=(clip:TransformClip):MotionTransform=>({...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})});
const anchorOrigin:Record<MotionTransform["anchor"],string>={"top-left":"0% 0%",top:"50% 0%","top-right":"100% 0%",left:"0% 50%",center:"50% 50%",right:"100% 50%","bottom-left":"0% 100%",bottom:"50% 100%","bottom-right":"100% 100%"};
const baseBox=(clip:TransformClip,project:Project)=>clip.type==="motion"?{width:project.canvas.width*.62,height:project.canvas.height*.34}:{width:project.canvas.width*.94,height:project.canvas.height*.94};

export const CanvasOverlay=({project,onCommand}:{project:Project;onCommand:OnCommand})=>{
  const{locale}=useStudioPreferences();const rootRef=useRef<HTMLDivElement>(null);const currentFrame=usePlayerStore(state=>state.currentFrame);const selectedClipId=useSelectionStore(state=>state.selectedClipId);const selectedClipIds=useSelectionStore(state=>state.selectedClipIds);const selectClip=useSelectionStore(state=>state.selectClip);
  const[displayScale,setDisplayScale]=useState(1);const[interaction,setInteraction]=useState<Interaction|null>(null);const[draft,setDraft]=useState<{clipId:string;transform:MotionTransform}|null>(null);const[guides,setGuides]=useState<CanvasGuide[]>([]);
  useEffect(()=>{const root=rootRef.current;if(!root)return;const update=()=>setDisplayScale(Math.max(.01,root.getBoundingClientRect().width/project.canvas.width));update();const observer=new ResizeObserver(update);observer.observe(root);return()=>observer.disconnect();},[project.canvas.width]);
  const active=useMemo(()=>project.tracks.filter(track=>!track.hidden).flatMap(track=>track.clips).filter(isTransformClip).filter(clip=>clip.enabled&&currentFrame>=clip.startFrame&&currentFrame<clip.startFrame+clip.durationInFrames).sort((a,b)=>a.layer-b.layer),[currentFrame,project.tracks]);
  const selected=active.find(clip=>clip.id===selectedClipId&&selectedClipIds.length===1);const currentTransform=selected?(draft?.clipId===selected.id?draft.transform:transformFor(selected)):undefined;
  const commandFor=(clip:TransformClip,transform:Partial<MotionTransform>):ProjectCommand=>clip.type==="motion"?{type:"update-motion-transform",clipId:clip.id,transform}:clip.type==="video"?{type:"update-video-properties",clipId:clip.id,transform}:{type:"update-broll-properties",clipId:clip.id,transform};
  const commit=async(clip:TransformClip,transform:MotionTransform)=>{const before=transformFor(clip);if(JSON.stringify(before)===JSON.stringify(transform))return;await onCommand(commandFor(clip,transform),locale==="zh-CN"?"画布变换已更新":"Canvas transform updated");};
  const start=(event:ReactPointerEvent,clip:TransformClip,mode:Interaction["mode"])=>{event.preventDefault();event.stopPropagation();selectClip(clip.id);const rect=rootRef.current?.getBoundingClientRect();if(!rect)return;const value=transformFor(clip);setDraft({clipId:clip.id,transform:value});setGuides([]);setInteraction({mode,pointerId:event.pointerId,clipId:clip.id,startClientX:event.clientX,startClientY:event.clientY,start:value,centerX:rect.left+rect.width/2+value.x*displayScale,centerY:rect.top+rect.height/2+value.y*displayScale});event.currentTarget.setPointerCapture(event.pointerId);};
  const move=(event:ReactPointerEvent)=>{if(!interaction||event.pointerId!==interaction.pointerId)return;const clip=active.find(item=>item.id===interaction.clipId);if(!clip)return;let next={...interaction.start};if(interaction.mode==="drag"){next.x=interaction.start.x+(event.clientX-interaction.startClientX)/displayScale;next.y=interaction.start.y+(event.clientY-interaction.startClientY)/displayScale;if(!event.altKey){const others=active.filter(item=>item.id!==clip.id).map(transformFor);const snapped=snapCanvasTransform(next,{width:project.canvas.width,height:project.canvas.height,threshold:9/displayScale,others});next=snapped.transform;setGuides(snapped.guides);}else setGuides([]);}else if(interaction.mode==="resize"){const box=baseBox(clip,project);next.scale=resizeScaleFromPointer(interaction.start.scale,(event.clientX-interaction.startClientX)/displayScale,(event.clientY-interaction.startClientY)/displayScale,box.width,box.height);setGuides([]);}else{next.rotation=normalizeRotation(rotationFromPointer(interaction.centerX,interaction.centerY,event.clientX,event.clientY));setGuides([]);}setDraft({clipId:clip.id,transform:next});};
  const finish=async(event:ReactPointerEvent)=>{if(!interaction||event.pointerId!==interaction.pointerId)return;const clip=active.find(item=>item.id===interaction.clipId);const value=draft?.clipId===interaction.clipId?draft.transform:interaction.start;setInteraction(null);setDraft(null);setGuides([]);if(clip)await commit(clip,value);};
  const nudge=(event:React.KeyboardEvent)=>{if(!selected||!currentTransform||!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key))return;event.preventDefault();event.stopPropagation();const amount=event.shiftKey?10:1;const patch={...currentTransform};if(event.key==="ArrowLeft")patch.x-=amount;if(event.key==="ArrowRight")patch.x+=amount;if(event.key==="ArrowUp")patch.y-=amount;if(event.key==="ArrowDown")patch.y+=amount;setDraft({clipId:selected.id,transform:patch});void commit(selected,patch).finally(()=>setDraft(null));};
  const layer=(delta:number)=>selected&&void onCommand({type:"set-clip-layer",clipId:selected.id,layer:selected.layer+delta},locale==="zh-CN"?"图层已更新":"Layer updated");
  const styleFor=(clip:TransformClip,value:MotionTransform)=>{const box=baseBox(clip,project);return{width:box.width*displayScale,height:box.height*displayScale,left:"50%",top:"50%",transform:`translate(-50%,-50%) translate(${value.x*displayScale}px,${value.y*displayScale}px) scale(${value.scale}) rotate(${value.rotation??0}deg)`,transformOrigin:anchorOrigin[value.anchor]};};
  return <div ref={rootRef} className="canvas-overlay" tabIndex={0} onKeyDown={nudge} onPointerDown={event=>{if(event.target===event.currentTarget)useSelectionStore.getState().clearSelection();}}>
    {guides.map((guide,index)=><i key={`${guide.axis}-${guide.value}-${index}`} className={`canvas-guide ${guide.axis} ${guide.kind}`} style={guide.axis==="x"?{left:`calc(50% + ${guide.value*displayScale}px)`}:{top:`calc(50% + ${guide.value*displayScale}px)`}}/>)}
    {active.map(clip=>{const value=draft?.clipId===clip.id?draft.transform:transformFor(clip);const selectedNow=selected?.id===clip.id;return <div key={clip.id} className={`canvas-object ${selectedNow?"selected":""} ${clip.type}`} style={styleFor(clip,value)} onPointerDown={event=>start(event,clip,"drag")} onPointerMove={move} onPointerUp={event=>void finish(event)} onPointerCancel={()=>{setInteraction(null);setDraft(null);setGuides([]);}}><span className="canvas-object-label">{clip.type==="motion"?(clip.engine==="hyperframes"?"HF":"FX"):clip.type.toUpperCase()}</span>{selectedNow?<><i className="canvas-handle nw"/><i className="canvas-handle ne"/><i className="canvas-handle sw"/><i className="canvas-handle se" onPointerDown={event=>start(event,clip,"resize")} onPointerMove={move} onPointerUp={event=>void finish(event)}/><button className="canvas-rotate" title={locale==="zh-CN"?"旋转":"Rotate"} onPointerDown={event=>start(event,clip,"rotate")} onPointerMove={move} onPointerUp={event=>void finish(event)}>↻</button></>:null}</div>;})}
    {selected&&currentTransform?<div className="canvas-floating-toolbar"><span>{selected.type==="motion"?selected.effectId:selected.type}</span><button onClick={()=>void commit(selected,{...currentTransform,x:0,y:0})}>{locale==="zh-CN"?"居中":"Center"}</button><button onClick={()=>layer(-1)}>↓ {locale==="zh-CN"?"后移":"Back"}</button><button onClick={()=>layer(1)}>↑ {locale==="zh-CN"?"前移":"Front"}</button><small>X {Math.round(currentTransform.x)} · Y {Math.round(currentTransform.y)} · {currentTransform.scale.toFixed(2)}× · {Math.round(currentTransform.rotation??0)}°</small></div>:null}
  </div>;
};
