import {describe,expect,it} from "vitest";
import {createProject} from "@/lib/project/factory";
import {applyProjectCommand} from "@/lib/project/commands";
import {collectTimelineSnapPoints,snapFrame,snapMove,snapResizeEnd} from "@/lib/timeline/snap";
import {normalizeRotation,resizeScaleFromPointer,snapCanvasTransform} from "@/lib/canvas/geometry";

describe("V2 M4 canvas and timeline foundations",()=>{
  it("persists rotation and clip layer through validated commands",()=>{let project=createProject({id:"m4-transform",name:"M4"});project=applyProjectCommand(project,{type:"add-clip",trackId:"motion-main",clip:{id:"m",type:"motion",engine:"remotion",effectId:"big-number",props:{},startFrame:0,durationInFrames:90,enabled:true,layer:1}});project=applyProjectCommand(project,{type:"update-motion-transform",clipId:"m",transform:{x:40,y:-20,scale:1.2,rotation:27}});project=applyProjectCommand(project,{type:"set-clip-layer",clipId:"m",layer:7});expect(project.tracks[2]!.clips[0]).toMatchObject({layer:7,transform:{x:40,y:-20,scale:1.2,rotation:27}});});
  it("snaps Canvas translation to center safe zones and other objects",()=>{const result=snapCanvasTransform({x:5,y:-4,scale:1,opacity:1,anchor:"center",rotation:0},{width:1080,height:1920,threshold:12,others:[]});expect(result.transform.x).toBe(0);expect(result.transform.y).toBe(0);expect(result.guides.map(g=>g.kind)).toEqual(["center","center"]);expect(resizeScaleFromPointer(1,108,192,1080,1920)).toBeCloseTo(1.1);expect(resizeScaleFromPointer(2,108,192,1080,1920)).toBeCloseTo(2.1);expect(normalizeRotation(270)).toBe(-90);});
  it("collects and applies timeline snap points for move and resize",()=>{let project=createProject({id:"m4-snap",name:"M4",durationInFrames:600});project=applyProjectCommand(project,{type:"add-clip",trackId:"motion-main",clip:{id:"m1",type:"motion",engine:"remotion",effectId:"big-number",props:{},startFrame:100,durationInFrames:60,enabled:true,layer:1}});project=applyProjectCommand(project,{type:"add-clip",trackId:"captions-main",clip:{id:"c1",type:"caption",text:"Hi",preset:"primary",emphasis:"none",keywords:[],startFrame:200,durationInFrames:30,enabled:true,layer:100}});project=applyProjectCommand(project,{type:"add-marker",marker:{id:"mk",frame:300,type:"note"}});const points=collectTimelineSnapPoints(project,{playhead:50,excludeClipId:"m1"});expect(points.some(point=>point.frame===200&&point.kind==="caption")).toBe(true);expect(points.some(point=>point.frame===300&&point.kind==="marker")).toBe(true);expect(snapFrame(52,points,3).frame).toBe(50);expect(snapMove(142,60,points,3).startFrame).toBe(140);expect(snapResizeEnd(100,98,points,3).durationInFrames).toBe(100);});
  it("splits a source-backed video without losing source continuity",()=>{let project=createProject({id:"m4-split",name:"M4",durationInFrames:300});project=applyProjectCommand(project,{type:"add-asset",asset:{id:"asset",kind:"video",relativePath:"input/source.mp4",durationInFrames:240}});project=applyProjectCommand(project,{type:"add-clip",trackId:"video-main",clip:{id:"v",type:"video",assetId:"asset",startFrame:20,durationInFrames:120,sourceStartFrame:30,volume:1,enabled:true,layer:0}});project=applyProjectCommand(project,{type:"split-clip",clipId:"v",frame:80,newClipId:"v-right"});const clips=project.tracks[0]!.clips.filter(clip=>clip.type==="video");expect(clips).toHaveLength(2);expect(clips[0]).toMatchObject({id:"v",startFrame:20,durationInFrames:60,sourceStartFrame:30});expect(clips[1]).toMatchObject({id:"v-right",startFrame:80,durationInFrames:60,sourceStartFrame:90});});
  it("splits b-roll from the matching source frame without an internal fade seam",()=>{let project=createProject({id:"m4-broll-split",name:"M4",durationInFrames:300});project=applyProjectCommand(project,{type:"add-asset",asset:{id:"asset",kind:"video",relativePath:"assets/source.mp4",durationInFrames:240}});project=applyProjectCommand(project,{type:"add-clip",trackId:"broll-main",clip:{id:"b",type:"broll",assetId:"asset",startFrame:40,durationInFrames:120,sourceStartFrame:15,fadeInFrames:10,fadeOutFrames:12,enabled:true,layer:2}});project=applyProjectCommand(project,{type:"split-clip",clipId:"b",frame:100,newClipId:"b-right"});const clips=project.tracks[3]!.clips.filter(clip=>clip.type==="broll");expect(clips).toHaveLength(2);expect(clips[0]).toMatchObject({id:"b",startFrame:40,durationInFrames:60,sourceStartFrame:15,fadeInFrames:10,fadeOutFrames:0});expect(clips[1]).toMatchObject({id:"b-right",startFrame:100,durationInFrames:60,sourceStartFrame:75,fadeInFrames:0,fadeOutFrames:12});project=applyProjectCommand(project,{type:"update-broll-properties",clipId:"b-right",sourceStartFrame:90});expect(project.tracks[3]!.clips[1]).toMatchObject({sourceStartFrame:90});});
  it("splits audio with source continuity and no artificial internal fades",()=>{let project=createProject({id:"m4-audio-split",name:"M4",durationInFrames:300});project=applyProjectCommand(project,{type:"add-asset",asset:{id:"asset",kind:"audio",relativePath:"assets/source.m4a",durationInFrames:240}});project=applyProjectCommand(project,{type:"add-clip",trackId:"audio-main",clip:{id:"a",type:"audio",assetId:"asset",startFrame:0,durationInFrames:180,sourceStartFrame:20,volume:.7,fadeInFrames:15,fadeOutFrames:18,enabled:true,layer:0}});project=applyProjectCommand(project,{type:"split-clip",clipId:"a",frame:90,newClipId:"a-right"});const clips=project.tracks[4]!.clips.filter(clip=>clip.type==="audio");expect(clips[0]).toMatchObject({durationInFrames:90,sourceStartFrame:20,fadeInFrames:15,fadeOutFrames:0});expect(clips[1]).toMatchObject({startFrame:90,durationInFrames:90,sourceStartFrame:110,fadeInFrames:0,fadeOutFrames:18});});
  it("restores a validated project snapshot as one new revision",()=>{let project=createProject({id:"m4-history",name:"Before"});const snapshot=structuredClone(project);project=applyProjectCommand(project,{type:"rename-project",name:"After"},{now:"2026-08-21T01:00:00.000Z"});const beforeRestoreRevision=project.project.revision;project=applyProjectCommand(project,{type:"restore-project-snapshot",snapshot},{now:"2026-08-21T01:01:00.000Z"});expect(project.project.name).toBe("Before");expect(project.project.revision).toBe(beforeRestoreRevision+1);expect(project.project.updatedAt).toBe("2026-08-21T01:01:00.000Z");});
});
