"use client";

import {useMemo,useRef,useState} from "react";
import type {ProjectCommand} from "@/lib/project/commands";
import {clampFrame} from "@/lib/timeline/frames";
import type {Clip} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {usePlayerStore} from "@/store/player-store";
import {useSelectionStore} from "@/store/selection-store";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";

type TimelineProps={project:Project;onCommand:(command:ProjectCommand,message:string)=>Promise<void>};
type DragState={mode:"move"|"resize";clip:Clip;originClientX:number;pixelsPerFrame:number};
type Marquee={trackId:string;startFrame:number;currentFrame:number}|null;
const TRACK_COLORS:Record<Clip["type"],string>={video:"#5b83c7",caption:"#9a7be0",motion:"#d58a48",broll:"#68b996",audio:"#c46f86"};
const TRACK_ICONS:Record<Clip["type"],string>={video:"▣",caption:"T",motion:"◆",broll:"▧",audio:"♪"};

export const Timeline=({project,onCommand}:TimelineProps)=>{
  const{locale,t}=useStudioPreferences();const[pixelsPerFrame,setPixelsPerFrame]=useState(1.1);const[drag,setDrag]=useState<DragState|null>(null);const[draft,setDraft]=useState<{clipId:string;startFrame:number;durationInFrames:number}|null>(null);const[marquee,setMarquee]=useState<Marquee>(null);const rulerRef=useRef<HTMLDivElement>(null);
  const currentFrame=usePlayerStore(state=>state.currentFrame);const requestSeek=usePlayerStore(state=>state.requestSeek);const selectedClipId=useSelectionStore(state=>state.selectedClipId);const selectedClipIds=useSelectionStore(state=>state.selectedClipIds);const selectedSceneId=useSelectionStore(state=>state.selectedSceneId);const selectClip=useSelectionStore(state=>state.selectClip);const selectClips=useSelectionStore(state=>state.selectClips);const toggleClip=useSelectionStore(state=>state.toggleClip);const selectScene=useSelectionStore(state=>state.selectScene);
  const width=Math.max(720,project.canvas.durationInFrames*pixelsPerFrame);const seconds=Math.ceil(project.canvas.durationInFrames/project.canvas.fps);const tickEvery=seconds>120?10:seconds>60?5:1;const ticks=useMemo(()=>{const values:number[]=[];for(let second=0;second<=seconds;second+=tickEvery)values.push(second);return values;},[seconds,tickEvery]);const scenes=useMemo(()=>[...project.scenes].sort((a,b)=>a.startFrame-b.startFrame),[project.scenes]);
  const seekFromClientX=(clientX:number)=>{const rect=rulerRef.current?.getBoundingClientRect();if(!rect)return;requestSeek(clampFrame((clientX-rect.left)/pixelsPerFrame,project.canvas.durationInFrames));};
  const startDrag=(event:React.PointerEvent,clip:Clip,mode:"move"|"resize",locked:boolean)=>{if(locked)return;event.preventDefault();event.stopPropagation();if(event.shiftKey){toggleClip(clip.id);return;}selectClip(clip.id);setDrag({mode,clip,originClientX:event.clientX,pixelsPerFrame});setDraft({clipId:clip.id,startFrame:clip.startFrame,durationInFrames:clip.durationInFrames});event.currentTarget.setPointerCapture(event.pointerId);};
  const updateDrag=(event:React.PointerEvent)=>{if(!drag)return;const delta=Math.round((event.clientX-drag.originClientX)/drag.pixelsPerFrame);if(drag.mode==="move")setDraft({clipId:drag.clip.id,startFrame:Math.max(0,drag.clip.startFrame+delta),durationInFrames:drag.clip.durationInFrames});else setDraft({clipId:drag.clip.id,startFrame:drag.clip.startFrame,durationInFrames:Math.max(1,drag.clip.durationInFrames+delta)});};
  const finishDrag=async()=>{const change=draft;const origin=drag;setDrag(null);setDraft(null);if(!change||!origin)return;if(change.startFrame===origin.clip.startFrame&&change.durationInFrames===origin.clip.durationInFrames)return;await onCommand({type:"update-clip-timing",clipId:change.clipId,startFrame:change.startFrame,durationInFrames:change.durationInFrames},t("timeline.updated"));};
  const startMarquee=(event:React.PointerEvent<HTMLDivElement>,trackId:string)=>{if(!event.shiftKey){seekFromClientX(event.clientX);return;}event.preventDefault();const rect=event.currentTarget.getBoundingClientRect();const frame=clampFrame((event.clientX-rect.left)/pixelsPerFrame,project.canvas.durationInFrames);setMarquee({trackId,startFrame:frame,currentFrame:frame});event.currentTarget.setPointerCapture(event.pointerId);};
  const moveMarquee=(event:React.PointerEvent<HTMLDivElement>)=>{if(!marquee)return;const rect=event.currentTarget.getBoundingClientRect();setMarquee({...marquee,currentFrame:clampFrame((event.clientX-rect.left)/pixelsPerFrame,project.canvas.durationInFrames)});};
  const finishMarquee=(trackId:string)=>{if(!marquee||marquee.trackId!==trackId)return;const from=Math.min(marquee.startFrame,marquee.currentFrame),to=Math.max(marquee.startFrame,marquee.currentFrame);const track=project.tracks.find(item=>item.id===trackId);const hits=track?.clips.filter(clip=>clip.startFrame<to&&clip.startFrame+clip.durationInFrames>from).map(clip=>clip.id)??[];selectClips(hits);setMarquee(null);};
  const displayTiming=(clip:Clip)=>draft?.clipId===clip.id?{startFrame:draft.startFrame,durationInFrames:draft.durationInFrames}:clip;const trackName=(type:Clip["type"],fallback:string)=>locale==="zh-CN"?({video:"视频",caption:"字幕",motion:"动效",broll:"B-roll",audio:"音频"}[type]??fallback):fallback;

  return <section className="timeline-panel"><header className="timeline-toolbar"><div><strong>{t("timeline.title")}</strong><span>{project.canvas.durationInFrames} {t("timeline.frames")} · {project.canvas.fps} fps</span></div><div className="timeline-actions"><button onClick={()=>setPixelsPerFrame(value=>Math.max(.25,value/1.35))}>−</button><span>{Math.round(pixelsPerFrame*100)}%</span><button onClick={()=>setPixelsPerFrame(value=>Math.min(6,value*1.35))}>+</button><i className="timeline-action-divider"/><button disabled={selectedClipIds.length!==1} onClick={()=>{if(!selectedClipId)return;const clip=project.tracks.flatMap(track=>track.clips).find(item=>item.id===selectedClipId);if(clip)void onCommand({type:"duplicate-clip",clipId:clip.id,newClipId:`${clip.id}-copy-${Date.now()}`,startFrame:Math.min(project.canvas.durationInFrames-1,clip.startFrame+clip.durationInFrames)},t("timeline.duplicated"));}}>⧉ {t("timeline.duplicate")}</button><button className="danger-lite" disabled={selectedClipIds.length!==1} onClick={()=>selectedClipId&&void onCommand({type:"remove-clip",clipId:selectedClipId},t("timeline.deleted")).then(()=>selectClip(null))}>⌫ {t("timeline.delete")}</button></div></header>
    <div className="timeline-scroll"><div className="timeline-grid" style={{width:width+142}}><div className="track-label ruler-label">{t("timeline.tracks")}</div><div ref={rulerRef} className="timeline-ruler" style={{width}} onPointerDown={event=>seekFromClientX(event.clientX)}>{ticks.map(second=><span key={second} style={{left:second*project.canvas.fps*pixelsPerFrame}}>{second}s</span>)}<i className="timeline-playhead" style={{left:currentFrame*pixelsPerFrame}}/></div>
      {scenes.length?<div className="timeline-track-row timeline-scene-strip"><div className="track-label"><strong><i>§</i>{locale==="zh-CN"?"场景":"Scenes"}</strong><small>{scenes.length}</small></div><div className="track-lane scene-lane" style={{width}}>{scenes.map((scene,index)=><button key={scene.id} className={`timeline-scene ${selectedSceneId===scene.id?"selected":""}`} style={{left:scene.startFrame*pixelsPerFrame,width:Math.max(18,(scene.endFrame-scene.startFrame)*pixelsPerFrame)}} title={`${scene.name} · ${scene.semanticType}`} onPointerDown={event=>{event.preventDefault();event.stopPropagation();selectScene(scene.id);requestSeek(scene.startFrame);}}><small>{String(index+1).padStart(2,"0")}</small><span>{scene.name}</span></button>)}<i className="timeline-playhead" style={{left:currentFrame*pixelsPerFrame}}/></div></div>:null}
      {project.tracks.map(track=><div className="timeline-track-row" key={track.id}><div className="track-label"><strong><i>{TRACK_ICONS[track.type]}</i>{trackName(track.type,track.name)}</strong><div><button className={track.locked?"active":""} onClick={()=>void onCommand({type:"set-track-state",trackId:track.id,locked:!track.locked},track.locked?"Track unlocked":"Track locked")}>L</button><button className={track.hidden?"active":""} onClick={()=>void onCommand({type:"set-track-state",trackId:track.id,hidden:!track.hidden},track.hidden?"Track shown":"Track hidden")}>H</button></div></div><div className={`track-lane ${track.hidden?"is-hidden":""}`} style={{width}} onPointerDown={event=>startMarquee(event,track.id)} onPointerMove={moveMarquee} onPointerUp={()=>finishMarquee(track.id)} onPointerCancel={()=>setMarquee(null)}>{marquee?.trackId===track.id?<i className="timeline-marquee" style={{left:Math.min(marquee.startFrame,marquee.currentFrame)*pixelsPerFrame,width:Math.max(2,Math.abs(marquee.currentFrame-marquee.startFrame)*pixelsPerFrame)}}/>:null}{track.clips.map(clip=>{const timing=displayTiming(clip);return <div data-clip-id={clip.id} key={clip.id} className={`timeline-clip ${selectedClipIds.includes(clip.id)?"selected":""}`} style={{left:timing.startFrame*pixelsPerFrame,width:Math.max(12,timing.durationInFrames*pixelsPerFrame),background:TRACK_COLORS[clip.type]}} onPointerDown={event=>startDrag(event,clip,"move",track.locked)} onPointerMove={updateDrag} onPointerUp={()=>void finishDrag()} onPointerCancel={()=>{setDrag(null);setDraft(null);}}><span>{trackName(clip.type,clip.type)} · {clip.id}</span><i className="resize-handle" onPointerDown={event=>startDrag(event,clip,"resize",track.locked)}/></div>;})}<i className="timeline-playhead" style={{left:currentFrame*pixelsPerFrame}}/></div></div>)}</div></div>
  </section>;
};
