"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import type {ProjectCommand} from "@/lib/project/commands";
import {collectTimelineSnapPoints,snapMove,snapResizeEnd} from "@/lib/timeline/snap";
import {clampFrame} from "@/lib/timeline/frames";
import {createRafLatestQueue} from "@/lib/studio/raf-latest";
import type {Clip} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {usePlayerStore} from "@/store/player-store";
import {useSelectionStore} from "@/store/selection-store";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {WaveformBars} from "./WaveformBars";
import {TimelinePlayhead} from "./TimelinePlayhead";
import {useTimelineProjectActions} from "./useTimelineProjectActions";

type Props={project:Project;onCommand:(command:ProjectCommand,message:string)=>Promise<void>};
type Drag={mode:"move"|"resize";clip:Clip;originX:number};
type Draft={clipId:string;startFrame:number;durationInFrames:number};
type DragPreview={draft:Draft;snapGuide:number|null};
type DragPreviewQueue={schedule:(value:DragPreview)=>void;cancel:()=>void;take:()=>DragPreview|undefined};
type Marquee={trackId:string;startFrame:number;currentFrame:number}|null;
const COLORS:Record<Clip["type"],string>={video:"#5b83c7",caption:"#9a7be0",motion:"#d58a48",broll:"#68b996",audio:"#c46f86"};const ICONS:Record<Clip["type"],string>={video:"▣",caption:"T",motion:"◆",broll:"▧",audio:"♪"};
const isInput=(target:EventTarget|null)=>target instanceof HTMLElement&&Boolean(target.closest("input,textarea,select,[contenteditable=true]"));
const currentFrame=()=>usePlayerStore.getState().currentFrame;

export const TimelineV2=({project,onCommand}:Props)=>{const{locale,t}=useStudioPreferences();const[pixelsPerFrame,setPixelsPerFrame]=useState(1.1);const[drag,setDrag]=useState<Drag|null>(null);const[draft,setDraft]=useState<Draft|null>(null);const[marquee,setMarquee]=useState<Marquee>(null);const[snapGuide,setSnapGuide]=useState<number|null>(null);const[snapEnabled,setSnapEnabled]=useState(()=>typeof window==="undefined"?true:localStorage.getItem("video-os-timeline-snap")!=="false");const rulerRef=useRef<HTMLDivElement>(null);const dragPreviewQueueRef=useRef<DragPreviewQueue|null>(null);const keyboardActionsRef=useRef<((event:KeyboardEvent)=>void)|null>(null);const requestSeek=usePlayerStore(s=>s.requestSeek);const selectedIds=useSelectionStore(s=>s.selectedClipIds);const selectedScene=useSelectionStore(s=>s.selectedSceneId);const selectClip=useSelectionStore(s=>s.selectClip);const selectClips=useSelectionStore(s=>s.selectClips);const toggleClip=useSelectionStore(s=>s.toggleClip);const selectScene=useSelectionStore(s=>s.selectScene);const clearSelection=useSelectionStore(s=>s.clearSelection);const{postCommand,postTransaction,undo,redo}=useTimelineProjectActions(project);
  useEffect(()=>localStorage.setItem("video-os-timeline-snap",String(snapEnabled)),[snapEnabled]);
  useEffect(()=>{const queue=createRafLatestQueue<DragPreview>(preview=>{setDraft(preview.draft);setSnapGuide(preview.snapGuide);},callback=>requestAnimationFrame(callback),id=>cancelAnimationFrame(id));dragPreviewQueueRef.current=queue;return()=>{queue.cancel();dragPreviewQueueRef.current=null;};},[]);
  const width=Math.max(720,project.canvas.durationInFrames*pixelsPerFrame);const seconds=Math.ceil(project.canvas.durationInFrames/project.canvas.fps);const tickEvery=seconds>120?10:seconds>60?5:1;const ticks=useMemo(()=>{const out:number[]=[];for(let i=0;i<=seconds;i+=tickEvery)out.push(i);return out;},[seconds,tickEvery]);const scenes=useMemo(()=>[...project.scenes].sort((a,b)=>a.startFrame-b.startFrame),[project.scenes]);
  const trackName=(type:Clip["type"],fallback:string)=>locale==="zh-CN"?({video:"视频",caption:"字幕",motion:"动效",broll:"B-roll",audio:"音频"}[type]??fallback):fallback;const seekAt=(clientX:number)=>{const rect=rulerRef.current?.getBoundingClientRect();if(rect)requestSeek(clampFrame((clientX-rect.left)/pixelsPerFrame,project.canvas.durationInFrames));};
  const startDrag=(event:React.PointerEvent,clip:Clip,mode:Drag["mode"],locked:boolean)=>{if(locked)return;event.preventDefault();event.stopPropagation();if(event.shiftKey){toggleClip(clip.id);return;}dragPreviewQueueRef.current?.cancel();selectClip(clip.id);setDrag({mode,clip,originX:event.clientX});setDraft({clipId:clip.id,startFrame:clip.startFrame,durationInFrames:clip.durationInFrames});setSnapGuide(null);event.currentTarget.setPointerCapture(event.pointerId);};
  const publishDragPreview=(preview:DragPreview)=>{const queue=dragPreviewQueueRef.current;if(queue)queue.schedule(preview);else{setDraft(preview.draft);setSnapGuide(preview.snapGuide);}};
  const moveDrag=(event:React.PointerEvent)=>{if(!drag)return;const delta=Math.round((event.clientX-drag.originX)/pixelsPerFrame);const threshold=Math.max(1,Math.round(8/pixelsPerFrame));const points=collectTimelineSnapPoints(project,{playhead:currentFrame(),excludeClipId:drag.clip.id});if(drag.mode==="move"){let start=Math.max(0,Math.min(project.canvas.durationInFrames-drag.clip.durationInFrames,drag.clip.startFrame+delta));let guide:number|null=null;if(snapEnabled&&!event.altKey){const result=snapMove(start,drag.clip.durationInFrames,points,threshold);start=Math.max(0,Math.min(project.canvas.durationInFrames-drag.clip.durationInFrames,result.startFrame));guide=result.guide?.frame??null;}publishDragPreview({draft:{clipId:drag.clip.id,startFrame:start,durationInFrames:drag.clip.durationInFrames},snapGuide:guide});}else{let duration=Math.max(1,Math.min(project.canvas.durationInFrames-drag.clip.startFrame,drag.clip.durationInFrames+delta));let guide:number|null=null;if(snapEnabled&&!event.altKey){const result=snapResizeEnd(drag.clip.startFrame,duration,points,threshold);duration=Math.max(1,Math.min(project.canvas.durationInFrames-drag.clip.startFrame,result.durationInFrames));guide=result.guide?.frame??null;}publishDragPreview({draft:{clipId:drag.clip.id,startFrame:drag.clip.startFrame,durationInFrames:duration},snapGuide:guide});}};
  const endDrag=async()=>{const queued=dragPreviewQueueRef.current?.take();const next=queued?.draft??draft,origin=drag;setDrag(null);setDraft(null);setSnapGuide(null);if(!next||!origin||next.startFrame===origin.clip.startFrame&&next.durationInFrames===origin.clip.durationInFrames)return;await postCommand({type:"update-clip-timing",clipId:next.clipId,startFrame:next.startFrame,durationInFrames:next.durationInFrames},t("timeline.updated"));};
  const cancelDrag=()=>{dragPreviewQueueRef.current?.cancel();setDrag(null);setDraft(null);setSnapGuide(null);};
  const startMarquee=(event:React.PointerEvent<HTMLDivElement>,trackId:string)=>{if(!event.shiftKey){seekAt(event.clientX);return;}event.preventDefault();const rect=event.currentTarget.getBoundingClientRect();const frame=clampFrame((event.clientX-rect.left)/pixelsPerFrame,project.canvas.durationInFrames);setMarquee({trackId,startFrame:frame,currentFrame:frame});event.currentTarget.setPointerCapture(event.pointerId);};const moveMarquee=(event:React.PointerEvent<HTMLDivElement>)=>{if(!marquee)return;const rect=event.currentTarget.getBoundingClientRect();setMarquee({...marquee,currentFrame:clampFrame((event.clientX-rect.left)/pixelsPerFrame,project.canvas.durationInFrames)});};const endMarquee=(trackId:string)=>{if(!marquee||marquee.trackId!==trackId)return;const from=Math.min(marquee.startFrame,marquee.currentFrame),to=Math.max(marquee.startFrame,marquee.currentFrame);const track=project.tracks.find(item=>item.id===trackId);selectClips(track?.clips.filter(clip=>clip.startFrame<to&&clip.startFrame+clip.durationInFrames>from).map(clip=>clip.id)??[]);setMarquee(null);};
  const addMarker=()=>void postCommand({type:"add-marker",marker:{id:`marker-${Date.now()}`,frame:currentFrame(),label:`M${project.markers.length+1}`,type:"note"}},locale==="zh-CN"?"标记已添加":"Marker added");
  const removeSelected=()=>{if(!selectedIds.length)return;if(selectedIds.length===1){void postCommand({type:"remove-clip",clipId:selectedIds[0]!},t("timeline.deleted")).then(clearSelection);return;}void postTransaction({id:`delete-${Date.now()}`,label:"Delete clips",commands:selectedIds.map(clipId=>({type:"remove-clip" as const,clipId}))},t("timeline.deleted")).then(clearSelection);};
  const duplicateSelected=()=>{const clips=project.tracks.flatMap(track=>track.clips).filter(clip=>selectedIds.includes(clip.id));if(!clips.length)return;const stamp=Date.now();const ids=clips.map((clip,index)=>`${clip.id}-copy-${stamp}-${index}`);const commands=clips.map((clip,index)=>({type:"duplicate-clip" as const,clipId:clip.id,newClipId:ids[index]!,startFrame:Math.max(0,Math.min(project.canvas.durationInFrames-clip.durationInFrames,clip.startFrame+clip.durationInFrames))}));const action=commands.length===1?postCommand(commands[0]!,t("timeline.duplicated")):postTransaction({id:`duplicate-${stamp}`,label:"Duplicate clips",commands},t("timeline.duplicated"));void action.then(()=>selectClips(ids));};
  const splitSelected=()=>{if(selectedIds.length!==1)return;const frame=currentFrame();const clip=project.tracks.flatMap(track=>track.clips).find(item=>item.id===selectedIds[0]);if(!clip||frame<=clip.startFrame||frame>=clip.startFrame+clip.durationInFrames)return;void postCommand({type:"split-clip",clipId:clip.id,frame,newClipId:`${clip.id}-split-${Date.now()}`},locale==="zh-CN"?"片段已拆分":"Clip split");};
  useEffect(()=>{keyboardActionsRef.current=(event:KeyboardEvent)=>{if(isInput(event.target))return;const mod=event.ctrlKey||event.metaKey;const key=event.key.toLowerCase();if(mod&&key==="z"){event.preventDefault();void(event.shiftKey?redo(locale==="zh-CN"?"重做":"Redo"):undo(locale==="zh-CN"?"撤销":"Undo"));return;}if(mod&&key==="d"){event.preventDefault();duplicateSelected();return;}if(event.code==="Space"){event.preventDefault();window.dispatchEvent(new CustomEvent("video-os-toggle-playback"));return;}if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();requestSeek(clampFrame(currentFrame()+(event.key==="ArrowRight"?1:-1)*(event.shiftKey?10:1),project.canvas.durationInFrames));return;}if(key==="m"){event.preventDefault();addMarker();return;}if(event.key==="Delete"||event.key==="Backspace"){event.preventDefault();removeSelected();return;}if(key==="s"){event.preventDefault();splitSelected();return;}if(event.key==="Escape")clearSelection();};});
  useEffect(()=>{const handler=(event:KeyboardEvent)=>keyboardActionsRef.current?.(event);window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[]);
  const timing=(clip:Clip)=>draft?.clipId===clip.id?draft:clip;const guide=<>{snapGuide!==null?<i className="timeline-snap-guide" style={{left:snapGuide*pixelsPerFrame}}/>:null}</>;
  return <section className="timeline-panel"><header className="timeline-toolbar"><div><strong>{t("timeline.title")}</strong><span>{project.canvas.durationInFrames} {t("timeline.frames")} · {project.canvas.fps} fps</span><span className="timeline-shortcut-hint">Space · ←/→ · M · S · ⌘D · ⌘Z</span></div><div className="timeline-actions"><button onClick={()=>setPixelsPerFrame(v=>Math.max(.25,v/1.35))}>−</button><span>{Math.round(pixelsPerFrame*100)}%</span><button onClick={()=>setPixelsPerFrame(v=>Math.min(6,v*1.35))}>+</button><button className={snapEnabled?"active":""} onClick={()=>setSnapEnabled(v=>!v)}>⌁ {locale==="zh-CN"?"吸附":"Snap"}</button><button onClick={addMarker}>◆ M <span className="timeline-marker-count">{project.markers.length}</span></button><button onClick={()=>void undo(locale==="zh-CN"?"撤销":"Undo")}>↶</button><button onClick={()=>void redo(locale==="zh-CN"?"重做":"Redo")}>↷</button><i className="timeline-action-divider"/><button disabled={!selectedIds.length} onClick={duplicateSelected}>⧉ {t("timeline.duplicate")}</button><button className="danger-lite" disabled={!selectedIds.length} onClick={removeSelected}>⌫ {t("timeline.delete")}</button></div></header>
    <div className="timeline-scroll"><div className="timeline-grid" style={{width:width+142}}><div className="track-label ruler-label">{t("timeline.tracks")}</div><div ref={rulerRef} className="timeline-ruler" style={{width}} onPointerDown={event=>seekAt(event.clientX)}>{ticks.map(second=><span key={second} style={{left:second*project.canvas.fps*pixelsPerFrame}}>{second}s</span>)}{project.markers.map(marker=><button key={marker.id} className="timeline-marker" style={{left:marker.frame*pixelsPerFrame}} title={`${marker.label??"Marker"} · f${marker.frame} · ${locale==="zh-CN"?"右键删除":"right-click to delete"}`} onClick={event=>{event.stopPropagation();requestSeek(marker.frame)}} onContextMenu={event=>{event.preventDefault();event.stopPropagation();void postCommand({type:"remove-marker",markerId:marker.id},locale==="zh-CN"?"标记已删除":"Marker removed");}}/>)}<TimelinePlayhead pixelsPerFrame={pixelsPerFrame}/>{guide}</div>
      {scenes.length?<div className="timeline-track-row timeline-scene-strip"><div className="track-label"><strong><i>§</i>{locale==="zh-CN"?"场景":"Scenes"}</strong><small>{scenes.length}</small></div><div className="track-lane scene-lane" style={{width}}>{scenes.map((scene,index)=><button key={scene.id} className={`timeline-scene ${selectedScene===scene.id?"selected":""}`} style={{left:scene.startFrame*pixelsPerFrame,width:Math.max(18,(scene.endFrame-scene.startFrame)*pixelsPerFrame)}} onPointerDown={event=>{event.preventDefault();event.stopPropagation();selectScene(scene.id);requestSeek(scene.startFrame);}}><small>{String(index+1).padStart(2,"0")}</small><span>{scene.name}</span></button>)}<TimelinePlayhead pixelsPerFrame={pixelsPerFrame}/>{guide}</div></div>:null}
      {project.tracks.map(track=><div className="timeline-track-row" key={track.id}><div className="track-label"><strong><i>{ICONS[track.type]}</i>{trackName(track.type,track.name)}</strong><div><button className={track.locked?"active":""} onClick={()=>void onCommand({type:"set-track-state",trackId:track.id,locked:!track.locked},track.locked?"Track unlocked":"Track locked")}>L</button><button className={track.hidden?"active":""} onClick={()=>void onCommand({type:"set-track-state",trackId:track.id,hidden:!track.hidden},track.hidden?"Track shown":"Track hidden")}>H</button></div></div><div className={`track-lane ${track.hidden?"is-hidden":""}`} style={{width}} onPointerDown={event=>startMarquee(event,track.id)} onPointerMove={moveMarquee} onPointerUp={()=>endMarquee(track.id)} onPointerCancel={()=>setMarquee(null)}>{marquee?.trackId===track.id?<i className="timeline-marquee" style={{left:Math.min(marquee.startFrame,marquee.currentFrame)*pixelsPerFrame,width:Math.max(2,Math.abs(marquee.currentFrame-marquee.startFrame)*pixelsPerFrame)}}/>:null}{track.clips.map(clip=>{const value=timing(clip);return <div data-clip-id={clip.id} key={clip.id} className={`timeline-clip ${selectedIds.includes(clip.id)?"selected":""} ${draft?.clipId===clip.id&&snapGuide!==null?"snap-preview":""}`} style={{left:value.startFrame*pixelsPerFrame,width:Math.max(12,value.durationInFrames*pixelsPerFrame),background:COLORS[clip.type]}} onPointerDown={event=>startDrag(event,clip,"move",track.locked)} onPointerMove={moveDrag} onPointerUp={()=>void endDrag()} onPointerCancel={cancelDrag}>{clip.type==="video"||clip.type==="audio"?<WaveformBars project={project} clip={clip}/>:null}<span>{trackName(clip.type,clip.type)} · {clip.id}</span><i className="resize-handle" onPointerDown={event=>startDrag(event,clip,"resize",track.locked)}/></div>;})}<TimelinePlayhead pixelsPerFrame={pixelsPerFrame}/>{guide}</div></div>)}</div></div>
  </section>;
};
