"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import type {CaptionVisualStyle} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {useSelectionStore} from "@/store/selection-store";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {LinkedStyleControls} from "./LinkedStyleControls";
import {m3Label} from "./m3-i18n";

export const CaptionInspector=({project,onCommand}:{project:Project;onCommand:(c:ProjectCommand,m:string)=>Promise<void>})=>{
  const id=useSelectionStore(state=>state.selectedClipId);const selectClip=useSelectionStore(state=>state.selectClip);const{locale,t}=useStudioPreferences();const clip=project.tracks.flatMap(track=>track.clips).find(item=>item.id===id);if(!clip||clip.type!=="caption")return null;
  const label=(key:Parameters<typeof m3Label>[1])=>m3Label(locale,key);
  const update=(patch:{preset?:"primary"|"minimal"|"bold";emphasis?:"none"|"numbers"|"keywords"|"both";keywords?:string[];style?:CaptionVisualStyle})=>void onCommand({type:"update-caption-style",clipId:clip.id,...patch},t("inspector.updated"));
  const updateTiming=(patch:{startFrame?:number;durationInFrames?:number})=>{const startFrame=Math.max(0,Math.min(project.canvas.durationInFrames-1,patch.startFrame??clip.startFrame));const durationInFrames=Math.max(1,Math.min(project.canvas.durationInFrames-startFrame,patch.durationInFrames??clip.durationInFrames));void onCommand({type:"update-clip-timing",clipId:clip.id,startFrame,durationInFrames},t("timeline.updated"));};
  const style=clip.style??{};
  return <div className="effect-inspector os-inspector">
    <header className="inspector-card-head"><small>{t("inspector.title")} · {clip.id.slice(0,14)}</small><div><span className="inspector-dot caption"/><h2>{t("caption.title")}</h2><em>{clip.preset}</em></div></header>
    <div data-inspector-section="linked"><LinkedStyleControls project={project} clip={clip} onCommand={onCommand}/></div>
    <section className="inspector-section" data-inspector-section="timing"><div className="inspector-section-title"><strong>{t("inspector.timing")}</strong><small>TIMING</small></div><div className="timing-grid"><label><span>{t("inspector.start")}</span><input type="number" min={0} max={project.canvas.durationInFrames-1} defaultValue={clip.startFrame} key={`${clip.id}-start-${clip.startFrame}`} onBlur={event=>updateTiming({startFrame:Number(event.target.value)})}/></label><label><span>{t("inspector.duration")}</span><input type="number" min={1} max={project.canvas.durationInFrames} defaultValue={clip.durationInFrames} key={`${clip.id}-duration-${clip.durationInFrames}`} onBlur={event=>updateTiming({durationInFrames:Number(event.target.value)})}/></label></div></section>
    <section className="inspector-section" data-inspector-section="content"><div className="inspector-section-title"><strong>{t("inspector.content")}</strong><small>{label("content")}</small></div><label className="inspector-field"><span>{t("caption.keywords")}</span><input defaultValue={clip.keywords.join(", ")} onBlur={event=>update({keywords:event.target.value.split(",").map(value=>value.trim()).filter(Boolean)})}/></label><div className="caption-copy">{clip.text}</div></section>
    <section className="inspector-section" data-inspector-section="typography"><div className="inspector-section-title"><strong>{locale==="zh-CN"?"排版":"Typography"}</strong><small>TYPE</small></div><div className="layout-number-grid"><label><span>{label("fontSize")}</span><input type="number" min={12} max={240} value={style.fontSize??50} onChange={event=>update({style:{fontSize:Number(event.target.value)}})}/></label><label><span>{label("fontWeight")}</span><input type="number" min={100} max={1000} step={100} value={style.fontWeight??850} onChange={event=>update({style:{fontWeight:Number(event.target.value)}})}/></label><label><span>{label("lineHeight")}</span><input type="number" min={.7} max={3} step={.05} value={style.lineHeight??1.25} onChange={event=>update({style:{lineHeight:Number(event.target.value)}})}/></label><label><span>{label("maxWidth")}</span><input type="number" min={20} max={100} value={style.maxWidth??86} onChange={event=>update({style:{maxWidth:Number(event.target.value)}})}/></label></div><label className="inspector-field"><span>{label("font")}</span><input value={style.fontFamily??project.brand.typography.captionFont} onBlur={event=>update({style:{fontFamily:event.target.value||project.brand.typography.captionFont}})}/></label></section>
    <section className="inspector-section" data-inspector-section="style"><div className="inspector-section-title"><strong>{t("inspector.style")}</strong><small>{label("style")}</small></div><label className="inspector-field"><span>{t("caption.preset")}</span><select value={clip.preset} onChange={event=>update({preset:event.target.value as "primary"|"minimal"|"bold"})}><option value="primary">{t("caption.primary")}</option><option value="minimal">{t("caption.minimal")}</option><option value="bold">{t("caption.bold")}</option></select></label><label className="inspector-field"><span>{t("caption.emphasis")}</span><select value={clip.emphasis} onChange={event=>update({emphasis:event.target.value as "none"|"numbers"|"keywords"|"both"})}><option value="none">{t("caption.none")}</option><option value="numbers">{t("caption.numbers")}</option><option value="keywords">{t("caption.keywordsOnly")}</option><option value="both">{t("caption.both")}</option></select></label><label className="inspector-field"><span>{label("fill")}</span><input type="color" value={style.fill??project.brand.colors.text} onChange={event=>update({style:{fill:event.target.value}})}/></label><label className="inspector-field"><span>{label("stroke")}</span><input value={style.stroke??""} placeholder="#000000" onBlur={event=>event.target.value&&update({style:{stroke:event.target.value}})}/></label><label className="inspector-field"><span>{label("shadow")}</span><input value={style.shadow??""} placeholder="0 4px 18px #000" onBlur={event=>event.target.value&&update({style:{shadow:event.target.value}})}/></label><label className="inspector-field"><span>{label("background")}</span><input value={style.background??""} placeholder="rgba(0,0,0,.68)" onBlur={event=>event.target.value&&update({style:{background:event.target.value}})}/></label></section>
    <section className="inspector-section" data-inspector-section="transform"><div className="inspector-section-title"><strong>{locale==="zh-CN"?"布局":"Layout"}</strong><small>TRANSFORM</small></div><label className="inspector-field"><span>{label("position")}</span><select value={style.position??"bottom"} onChange={event=>update({style:{position:event.target.value as "top"|"center"|"bottom"}})}><option value="top">{label("top")}</option><option value="center">{label("center")}</option><option value="bottom">{label("bottom")}</option></select></label><label className="inspector-field"><span>{label("alignment")}</span><select value={style.alignment??"center"} onChange={event=>update({style:{alignment:event.target.value as "left"|"center"|"right"}})}><option value="left">{label("left")}</option><option value="center">{label("center")}</option><option value="right">{label("right")}</option></select></label></section>
    <button className="inspector-delete" onClick={()=>void onCommand({type:"remove-clip",clipId:clip.id},t("timeline.deleted")).then(()=>selectClip(null))}>▱ {t("inspector.delete")}</button>
  </div>;
};