"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import {DEFAULT_MOTION_TRANSFORM,type MotionTransform} from "@/schemas/clip";
import type {Project} from "@/schemas/project";

type OnCommand=(command:ProjectCommand,message:string)=>Promise<void>;
const Timing=({clip,onCommand}:{clip:{id:string;startFrame:number;durationInFrames:number};onCommand:OnCommand})=><section className="inspector-section"><div className="inspector-section-title"><strong>Timing</strong><small>TIMING</small></div><div className="timing-grid"><label><span>Start</span><input type="number" defaultValue={clip.startFrame} onBlur={e=>void onCommand({type:"update-clip-timing",clipId:clip.id,startFrame:Number(e.target.value)},"Timing updated")}/></label><label><span>Duration</span><input type="number" min={1} defaultValue={clip.durationInFrames} onBlur={e=>void onCommand({type:"update-clip-timing",clipId:clip.id,durationInFrames:Number(e.target.value)},"Timing updated")}/></label></div></section>;
const Transform=({value,onChange}:{value:MotionTransform;onChange:(patch:Partial<MotionTransform>)=>void})=><div className="layout-number-grid"><label><span>X</span><input type="number" value={value.x} onChange={e=>onChange({x:Number(e.target.value)})}/></label><label><span>Y</span><input type="number" value={value.y} onChange={e=>onChange({y:Number(e.target.value)})}/></label><label><span>Scale</span><input type="number" min={.1} max={5} step={.05} value={value.scale} onChange={e=>onChange({scale:Number(e.target.value)})}/></label><label><span>Opacity</span><input type="number" min={0} max={1} step={.05} value={value.opacity} onChange={e=>onChange({opacity:Number(e.target.value)})}/></label></div>;

export const VideoInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"video"}>;onCommand:OnCommand})=>{const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};return <div className="os-inspector"><header className="inspector-card-head"><small>VIDEO INSPECTOR</small><div><h2>Video</h2><em>{clip.id}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><div className="inspector-section-title"><strong>Media</strong><small>VIDEO</small></div><label className="inspector-field"><span>Fit</span><select value={clip.fit??"contain"} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,fit:e.target.value as "contain"|"cover"},"Video updated")}><option value="contain">Contain</option><option value="cover">Cover</option></select></label><label className="inspector-field"><span>Volume</span><input type="number" min={0} max={2} step={.05} value={clip.volume} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,volume:Number(e.target.value)},"Video updated")}/></label><label className="inspector-field"><span>Mute</span><input type="checkbox" checked={clip.muted??false} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,muted:e.target.checked},"Video updated")}/></label><small>Source start f{clip.sourceStartFrame}</small></section><section className="inspector-section"><div className="inspector-section-title"><strong>Layout</strong><small>TRANSFORM</small></div><Transform value={transform} onChange={patch=>void onCommand({type:"update-video-properties",clipId:clip.id,transform:patch},"Video transform updated")}/></section></div>;};

export const BrollInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"broll"}>;onCommand:OnCommand})=>{const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};return <div className="os-inspector"><header className="inspector-card-head"><small>B-ROLL INSPECTOR</small><div><h2>B-roll</h2><em>{clip.id}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><label className="inspector-field"><span>Fit</span><select value={clip.fit??"cover"} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fit:e.target.value as "cover"|"contain"},"B-roll updated")}><option value="cover">Cover</option><option value="contain">Contain</option></select></label><label className="inspector-field"><span>Volume</span><input type="number" min={0} max={2} step={.05} value={clip.volume??1} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,volume:Number(e.target.value)},"B-roll updated")}/></label><label className="inspector-field"><span>Mute</span><input type="checkbox" checked={clip.muted??true} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,muted:e.target.checked},"B-roll updated")}/></label><div className="layout-number-grid"><label><span>Fade In</span><input type="number" min={0} value={clip.fadeInFrames??0} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fadeInFrames:Number(e.target.value)},"B-roll updated")}/></label><label><span>Fade Out</span><input type="number" min={0} value={clip.fadeOutFrames??0} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fadeOutFrames:Number(e.target.value)},"B-roll updated")}/></label></div><Transform value={transform} onChange={patch=>void onCommand({type:"update-broll-properties",clipId:clip.id,transform:patch},"B-roll transform updated")}/></section></div>;};

export const AudioInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"audio"}>;onCommand:OnCommand})=><div className="os-inspector"><header className="inspector-card-head"><small>AUDIO INSPECTOR</small><div><h2>Audio</h2><em>{clip.role??"bgm"}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><label className="inspector-field"><span>Role</span><select value={clip.role??"bgm"} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,role:e.target.value as "voice"|"bgm"|"sfx"},"Audio updated")}><option value="voice">Voice</option><option value="bgm">BGM</option><option value="sfx">SFX</option></select></label><label className="inspector-field"><span>Volume</span><input type="number" min={0} max={2} step={.05} value={clip.volume} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,volume:Number(e.target.value)},"Audio updated")}/></label><label className="inspector-field"><span>Mute</span><input type="checkbox" checked={clip.muted??false} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,muted:e.target.checked},"Audio updated")}/></label><div className="layout-number-grid"><label><span>Fade In</span><input type="number" min={0} value={clip.fadeInFrames??0} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,fadeInFrames:Number(e.target.value)},"Audio updated")}/></label><label><span>Fade Out</span><input type="number" min={0} value={clip.fadeOutFrames??0} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,fadeOutFrames:Number(e.target.value)},"Audio updated")}/></label></div></section></div>;
