"use client";

import type {KeyboardEvent} from "react";
import type {ProjectCommand} from "@/lib/project/commands";
import {DEFAULT_MOTION_TRANSFORM,type MotionTransform} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {m3Label as label} from "./m3-i18n";

type OnCommand=(command:ProjectCommand,message:string)=>Promise<void>;
const blurOnEnter=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key==="Enter")event.currentTarget.blur();};
const commitNumber=(event:React.FocusEvent<HTMLInputElement>,current:number,commit:(value:number)=>void)=>{const value=Number(event.target.value);if(Number.isFinite(value)&&value!==current)commit(value);};

const Timing=({clip,onCommand}:{clip:{id:string;startFrame:number;durationInFrames:number};onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);return <section className="inspector-section"><div className="inspector-section-title"><strong>{l("timing")}</strong><small>TIMING</small></div><div className="timing-grid"><label><span>{l("start")}</span><input type="number" defaultValue={clip.startFrame} key={`${clip.id}-start-${clip.startFrame}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,clip.startFrame,value=>void onCommand({type:"update-clip-timing",clipId:clip.id,startFrame:value},l("timing")))}/></label><label><span>{l("duration")}</span><input type="number" min={1} defaultValue={clip.durationInFrames} key={`${clip.id}-duration-${clip.durationInFrames}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,clip.durationInFrames,value=>void onCommand({type:"update-clip-timing",clipId:clip.id,durationInFrames:value},l("timing")))}/></label></div></section>};
const Transform=({value,onChange}:{value:MotionTransform;onChange:(patch:Partial<MotionTransform>)=>void})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const rotation=value.rotation??0;return <div className="layout-number-grid"><label><span>X</span><input type="number" defaultValue={value.x} key={`x-${value.x}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,value.x,x=>onChange({x}))}/></label><label><span>Y</span><input type="number" defaultValue={value.y} key={`y-${value.y}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,value.y,y=>onChange({y}))}/></label><label><span>{l("scale")}</span><input type="number" min={.1} max={5} step={.05} defaultValue={value.scale} key={`scale-${value.scale}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,value.scale,scale=>onChange({scale}))}/></label><label><span>{l("opacity")}</span><input type="number" min={0} max={1} step={.05} defaultValue={value.opacity} key={`opacity-${value.opacity}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,value.opacity,opacity=>onChange({opacity}))}/></label><label><span>{l("rotation")}</span><input type="number" step={1} defaultValue={rotation} key={`rotation-${rotation}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,rotation,rotationValue=>onChange({rotation:rotationValue}))}/></label></div>};

export const VideoInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"video"}>;onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};return <div className="os-inspector"><header className="inspector-card-head"><small>{l("videoInspector").toUpperCase()}</small><div><h2>{locale==="zh-CN"?"视频":"Video"}</h2><em>{clip.id}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><div className="inspector-section-title"><strong>{l("media")}</strong><small>{l("media")}</small></div><label className="inspector-field"><span>{l("fit")}</span><select value={clip.fit??"contain"} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,fit:e.target.value as "contain"|"cover"},l("media"))}><option value="contain">{l("contain")}</option><option value="cover">{l("cover")}</option></select></label><label className="inspector-field"><span>{l("volume")}</span><input type="number" min={0} max={2} step={.05} defaultValue={clip.volume} key={`${clip.id}-volume-${clip.volume}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,clip.volume,volume=>void onCommand({type:"update-video-properties",clipId:clip.id,volume},l("media")))}/></label><label className="inspector-field"><span>{l("mute")}</span><input type="checkbox" checked={clip.muted??false} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,muted:e.target.checked},l("media"))}/></label><small>{l("sourceStart")} f{clip.sourceStartFrame}</small></section><section className="inspector-section"><div className="inspector-section-title"><strong>{l("layout")}</strong><small>TRANSFORM</small></div><Transform value={transform} onChange={patch=>void onCommand({type:"update-video-properties",clipId:clip.id,transform:patch},l("layout"))}/></section></div>};

export const BrollInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"broll"}>;onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};const sourceStart=clip.sourceStartFrame??0;const volume=clip.volume??1;const fadeIn=clip.fadeInFrames??0;const fadeOut=clip.fadeOutFrames??0;return <div className="os-inspector"><header className="inspector-card-head"><small>{l("brollInspector").toUpperCase()}</small><div><h2>B-roll</h2><em>{clip.id}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><label className="inspector-field"><span>{l("sourceStart")}</span><input type="number" min={0} defaultValue={sourceStart} key={`${clip.id}-sourceStart-${sourceStart}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,sourceStart,sourceStartFrame=>void onCommand({type:"update-broll-properties",clipId:clip.id,sourceStartFrame},"B-roll"))}/></label><label className="inspector-field"><span>{l("fit")}</span><select value={clip.fit??"cover"} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fit:e.target.value as "cover"|"contain"},"B-roll")}><option value="cover">{l("cover")}</option><option value="contain">{l("contain")}</option></select></label><label className="inspector-field"><span>{l("volume")}</span><input type="number" min={0} max={2} step={.05} defaultValue={volume} key={`${clip.id}-volume-${volume}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,volume,next=>void onCommand({type:"update-broll-properties",clipId:clip.id,volume:next},"B-roll"))}/></label><label className="inspector-field"><span>{l("mute")}</span><input type="checkbox" checked={clip.muted??true} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,muted:e.target.checked},"B-roll")}/></label><div className="layout-number-grid"><label><span>{l("fadeIn")}</span><input type="number" min={0} defaultValue={fadeIn} key={`${clip.id}-fadeIn-${fadeIn}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,fadeIn,fadeInFrames=>void onCommand({type:"update-broll-properties",clipId:clip.id,fadeInFrames},"B-roll"))}/></label><label><span>{l("fadeOut")}</span><input type="number" min={0} defaultValue={fadeOut} key={`${clip.id}-fadeOut-${fadeOut}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,fadeOut,fadeOutFrames=>void onCommand({type:"update-broll-properties",clipId:clip.id,fadeOutFrames},"B-roll"))}/></label></div><Transform value={transform} onChange={patch=>void onCommand({type:"update-broll-properties",clipId:clip.id,transform:patch},"B-roll")}/></section></div>};

export const AudioInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"audio"}>;onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const fadeIn=clip.fadeInFrames??0;const fadeOut=clip.fadeOutFrames??0;return <div className="os-inspector"><header className="inspector-card-head"><small>{l("audioInspector").toUpperCase()}</small><div><h2>{locale==="zh-CN"?"音频":"Audio"}</h2><em>{clip.role??"bgm"}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><label className="inspector-field"><span>{l("role")}</span><select value={clip.role??"bgm"} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,role:e.target.value as "voice"|"bgm"|"sfx"},"Audio")}><option value="voice">{l("voice")}</option><option value="bgm">{l("bgm")}</option><option value="sfx">{l("sfx")}</option></select></label><label className="inspector-field"><span>{l("volume")}</span><input type="number" min={0} max={2} step={.05} defaultValue={clip.volume} key={`${clip.id}-volume-${clip.volume}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,clip.volume,volume=>void onCommand({type:"update-audio-properties",clipId:clip.id,volume},"Audio"))}/></label><label className="inspector-field"><span>{l("mute")}</span><input type="checkbox" checked={clip.muted??false} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,muted:e.target.checked},"Audio")}/></label><div className="layout-number-grid"><label><span>{l("fadeIn")}</span><input type="number" min={0} defaultValue={fadeIn} key={`${clip.id}-fadeIn-${fadeIn}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,fadeIn,fadeInFrames=>void onCommand({type:"update-audio-properties",clipId:clip.id,fadeInFrames},"Audio"))}/></label><label><span>{l("fadeOut")}</span><input type="number" min={0} defaultValue={fadeOut} key={`${clip.id}-fadeOut-${fadeOut}`} onKeyDown={blurOnEnter} onBlur={e=>commitNumber(e,fadeOut,fadeOutFrames=>void onCommand({type:"update-audio-properties",clipId:clip.id,fadeOutFrames},"Audio"))}/></label></div></section></div>};
