"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import {DEFAULT_MOTION_TRANSFORM,type MotionTransform} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {m3Label as label} from "./m3-i18n";

type OnCommand=(command:ProjectCommand,message:string)=>Promise<void>;
const Timing=({clip,onCommand}:{clip:{id:string;startFrame:number;durationInFrames:number};onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);return <section className="inspector-section"><div className="inspector-section-title"><strong>{l("timing")}</strong><small>TIMING</small></div><div className="timing-grid"><label><span>{l("start")}</span><input type="number" defaultValue={clip.startFrame} onBlur={e=>void onCommand({type:"update-clip-timing",clipId:clip.id,startFrame:Number(e.target.value)},l("timing"))}/></label><label><span>{l("duration")}</span><input type="number" min={1} defaultValue={clip.durationInFrames} onBlur={e=>void onCommand({type:"update-clip-timing",clipId:clip.id,durationInFrames:Number(e.target.value)},l("timing"))}/></label></div></section>};
const Transform=({value,onChange}:{value:MotionTransform;onChange:(patch:Partial<MotionTransform>)=>void})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);return <div className="layout-number-grid"><label><span>X</span><input type="number" value={value.x} onChange={e=>onChange({x:Number(e.target.value)})}/></label><label><span>Y</span><input type="number" value={value.y} onChange={e=>onChange({y:Number(e.target.value)})}/></label><label><span>{l("scale")}</span><input type="number" min={.1} max={5} step={.05} value={value.scale} onChange={e=>onChange({scale:Number(e.target.value)})}/></label><label><span>{l("opacity")}</span><input type="number" min={0} max={1} step={.05} value={value.opacity} onChange={e=>onChange({opacity:Number(e.target.value)})}/></label><label><span>{l("rotation")}</span><input type="number" step={1} value={value.rotation??0} onChange={e=>onChange({rotation:Number(e.target.value)})}/></label></div>};

export const VideoInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"video"}>;onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};return <div className="os-inspector"><header className="inspector-card-head"><small>{l("videoInspector").toUpperCase()}</small><div><h2>{locale==="zh-CN"?"视频":"Video"}</h2><em>{clip.id}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><div className="inspector-section-title"><strong>{l("media")}</strong><small>{l("media")}</small></div><label className="inspector-field"><span>{l("fit")}</span><select value={clip.fit??"contain"} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,fit:e.target.value as "contain"|"cover"},l("media"))}><option value="contain">{l("contain")}</option><option value="cover">{l("cover")}</option></select></label><label className="inspector-field"><span>{l("volume")}</span><input type="number" min={0} max={2} step={.05} value={clip.volume} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,volume:Number(e.target.value)},l("media"))}/></label><label className="inspector-field"><span>{l("mute")}</span><input type="checkbox" checked={clip.muted??false} onChange={e=>void onCommand({type:"update-video-properties",clipId:clip.id,muted:e.target.checked},l("media"))}/></label><small>{l("sourceStart")} f{clip.sourceStartFrame}</small></section><section className="inspector-section"><div className="inspector-section-title"><strong>{l("layout")}</strong><small>TRANSFORM</small></div><Transform value={transform} onChange={patch=>void onCommand({type:"update-video-properties",clipId:clip.id,transform:patch},l("layout"))}/></section></div>};

export const BrollInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"broll"}>;onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};return <div className="os-inspector"><header className="inspector-card-head"><small>{l("brollInspector").toUpperCase()}</small><div><h2>B-roll</h2><em>{clip.id}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><label className="inspector-field"><span>{l("fit")}</span><select value={clip.fit??"cover"} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fit:e.target.value as "cover"|"contain"},"B-roll")}><option value="cover">{l("cover")}</option><option value="contain">{l("contain")}</option></select></label><label className="inspector-field"><span>{l("volume")}</span><input type="number" min={0} max={2} step={.05} value={clip.volume??1} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,volume:Number(e.target.value)},"B-roll")}/></label><label className="inspector-field"><span>{l("mute")}</span><input type="checkbox" checked={clip.muted??true} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,muted:e.target.checked},"B-roll")}/></label><div className="layout-number-grid"><label><span>{l("fadeIn")}</span><input type="number" min={0} value={clip.fadeInFrames??0} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fadeInFrames:Number(e.target.value)},"B-roll")}/></label><label><span>{l("fadeOut")}</span><input type="number" min={0} value={clip.fadeOutFrames??0} onChange={e=>void onCommand({type:"update-broll-properties",clipId:clip.id,fadeOutFrames:Number(e.target.value)},"B-roll")}/></label></div><Transform value={transform} onChange={patch=>void onCommand({type:"update-broll-properties",clipId:clip.id,transform:patch},"B-roll")}/></section></div>};

export const AudioInspector=({clip,onCommand}:{clip:Extract<Project["tracks"][number]["clips"][number],{type:"audio"}>;onCommand:OnCommand})=>{const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);return <div className="os-inspector"><header className="inspector-card-head"><small>{l("audioInspector").toUpperCase()}</small><div><h2>{locale==="zh-CN"?"音频":"Audio"}</h2><em>{clip.role??"bgm"}</em></div></header><Timing clip={clip} onCommand={onCommand}/><section className="inspector-section"><label className="inspector-field"><span>{l("role")}</span><select value={clip.role??"bgm"} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,role:e.target.value as "voice"|"bgm"|"sfx"},"Audio")}><option value="voice">{l("voice")}</option><option value="bgm">{l("bgm")}</option><option value="sfx">{l("sfx")}</option></select></label><label className="inspector-field"><span>{l("volume")}</span><input type="number" min={0} max={2} step={.05} value={clip.volume} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,volume:Number(e.target.value)},"Audio")}/></label><label className="inspector-field"><span>{l("mute")}</span><input type="checkbox" checked={clip.muted??false} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,muted:e.target.checked},"Audio")}/></label><div className="layout-number-grid"><label><span>{l("fadeIn")}</span><input type="number" min={0} value={clip.fadeInFrames??0} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,fadeInFrames:Number(e.target.value)},"Audio")}/></label><label><span>{l("fadeOut")}</span><input type="number" min={0} value={clip.fadeOutFrames??0} onChange={e=>void onCommand({type:"update-audio-properties",clipId:clip.id,fadeOutFrames:Number(e.target.value)},"Audio")}/></label></div></section></div>};
