"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import {DEFAULT_MOTION_TRANSFORM,type MotionTransform} from "@/schemas/clip";
import type {Project} from "@/schemas/project";
import {EFFECTS_BY_ID} from "@/shared/effects/registry";
import type {EffectField} from "@/shared/effects/types";
import {useSelectionStore} from "@/store/selection-store";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {translateEffectName,type StudioMessageKey} from "@/lib/i18n/studio";
import {EffectPresetControls} from "./EffectPresetControls";
import {LinkedStyleControls} from "./LinkedStyleControls";
import {m3Label} from "./m3-i18n";

const coerce=(field:EffectField,value:string|boolean)=>field.type==="number"||field.type==="slider"?Number(value):value;
const groupForField=(field:EffectField):"content"|"timing"|"style"=>{const key=field.key.toLowerCase();if(key.includes("animation")||key.includes("speed")||key.includes("delay")||key.includes("interval"))return"timing";if(field.type==="color"||key.includes("color")||key.includes("font")||key.includes("background")||key.includes("shadow")||key.includes("glow"))return"style";return"content";};
const anchors:MotionTransform["anchor"][]=["top-left","top","top-right","left","center","right","bottom-left","bottom","bottom-right"];
const anchorI18n:Record<MotionTransform["anchor"],StudioMessageKey>={"top-left":"layout.anchor.topLeft",top:"layout.anchor.top","top-right":"layout.anchor.topRight",left:"layout.anchor.left",center:"layout.anchor.center",right:"layout.anchor.right","bottom-left":"layout.anchor.bottomLeft",bottom:"layout.anchor.bottom","bottom-right":"layout.anchor.bottomRight"};

export const MotionInspector=({project,onCommand}:{project:Project;onCommand:(command:ProjectCommand,message:string)=>Promise<void>})=>{
 const id=useSelectionStore(s=>s.selectedClipId);const selectClip=useSelectionStore(s=>s.selectClip);const{locale,t}=useStudioPreferences();const clip=project.tracks.flatMap(t=>t.clips).find(c=>c.id===id);if(!clip||clip.type!=="motion")return null;
 const label=(key:Parameters<typeof m3Label>[1])=>m3Label(locale,key);
 const effect=clip.engine==="remotion"?EFFECTS_BY_ID[clip.effectId]:undefined;const displayName=translateEffectName(locale,clip.effectId,effect?.name??clip.effectId);let props:Record<string,unknown>=clip.props;if(effect){const parsed=effect.schema.safeParse(clip.props);props=parsed.success?parsed.data:effect.defaults;}const transform={...DEFAULT_MOTION_TRANSFORM,...(clip.transform??{})};
 const updateProp=(field:EffectField,value:string|boolean)=>{if(!effect)return;const parsed=effect.schema.safeParse({...props,[field.key]:coerce(field,value)});if(parsed.success)void onCommand({type:"update-motion-props",clipId:clip.id,props:parsed.data},t("inspector.updated"));};
 const updateTiming=(patch:{startFrame?:number;durationInFrames?:number})=>void onCommand({type:"update-clip-timing",clipId:clip.id,...patch},t("timeline.updated"));
 const updateTransform=(patch:Partial<MotionTransform>)=>void onCommand({type:"update-motion-transform",clipId:clip.id,transform:patch},t("inspector.updated"));
 const grouped=effect?{content:effect.fields.filter(f=>groupForField(f)==="content"),timing:effect.fields.filter(f=>groupForField(f)==="timing"),style:effect.fields.filter(f=>groupForField(f)==="style")}:{content:[],timing:[],style:[]};
 const field=(f:EffectField)=><label className="inspector-field" key={f.key}><span>{f.label}</span>{f.type==="switch"?<input type="checkbox" checked={Boolean(props[f.key])} onChange={e=>updateProp(f,e.target.checked)}/>:f.type==="select"?<select value={String(props[f.key]??"")} onChange={e=>updateProp(f,e.target.value)}>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==="slider"?<input type="range" min={f.min} max={f.max} step={f.step} value={Number(props[f.key]??0)} onChange={e=>updateProp(f,e.target.value)}/>:<input type={f.type==="color"?"color":f.type==="number"?"number":"text"} value={String(props[f.key]??"")} min={f.min} max={f.max} step={f.step} onChange={e=>updateProp(f,e.target.value)}/>}</label>;
 return <div className="effect-inspector os-inspector"><header className="inspector-card-head"><small>{t("inspector.title")} · {clip.id.slice(0,14)}</small><div><span className="inspector-dot"/><h2>{displayName}</h2><em>{clip.engine}</em></div></header><EffectPresetControls project={project} clipId={clip.id} effectId={clip.effectId} engine={clip.engine} onCommand={onCommand}/><LinkedStyleControls project={project} clip={clip} onCommand={onCommand}/><section className="inspector-section"><div className="inspector-section-title"><strong>{label("timing")}</strong><small>TIMING</small></div><div className="timing-grid"><label><span>{label("start")}</span><input type="number" value={clip.startFrame} onChange={e=>updateTiming({startFrame:Number(e.target.value)})}/></label><label><span>{label("duration")}</span><input type="number" min={1} value={clip.durationInFrames} onChange={e=>updateTiming({durationInFrames:Number(e.target.value)})}/></label></div></section>{effect?(["content","timing","style"] as const).map(g=>grouped[g].length?<section className="inspector-section" key={g}><div className="inspector-section-title"><strong>{label(g)}</strong><small>{g.toUpperCase()}</small></div>{grouped[g].map(field)}</section>:null):<section className="inspector-section"><p>{label("hyperframesHelp")}</p></section>}<section className="inspector-section"><div className="inspector-section-title"><strong>{label("layout")}</strong><small>TRANSFORM</small></div><div className="layout-number-grid"><label><span>X</span><input type="number" value={transform.x} onChange={e=>updateTransform({x:Number(e.target.value)})}/></label><label><span>Y</span><input type="number" value={transform.y} onChange={e=>updateTransform({y:Number(e.target.value)})}/></label><label><span>{label("scale")}</span><input type="number" min={.1} max={5} step={.05} value={transform.scale} onChange={e=>updateTransform({scale:Number(e.target.value)})}/></label><label><span>{label("opacity")}</span><input type="number" min={0} max={1} step={.05} value={transform.opacity} onChange={e=>updateTransform({opacity:Number(e.target.value)})}/></label></div><div className="anchor-control"><span>{label("anchor")}</span><div className="anchor-grid">{anchors.map(a=><button key={a} className={transform.anchor===a?"active":""} title={t(anchorI18n[a])} onClick={()=>updateTransform({anchor:a})}><i/></button>)}</div></div></section><button className="inspector-delete" onClick={()=>void onCommand({type:"remove-clip",clipId:clip.id},t("timeline.deleted")).then(()=>selectClip(null))}>▱ {label("delete")}</button></div>;
};
