"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import type {Project} from "@/schemas/project";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {m3Label as label} from "./m3-i18n";

export const ProjectInspector=({project,onCommand}:{project:Project;onCommand:(command:ProjectCommand,message:string)=>Promise<void>})=>{
  const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const brand=project.brand;const set=(next:Project["brand"])=>void onCommand({type:"set-brand",brand:next},locale==="zh-CN"?"视频品牌已更新":"Video brand updated");
  const colorLabels={primary:l("primary"),data:l("data"),success:l("success"),text:l("text"),background:l("background")};
  return <div className="os-inspector"><header className="inspector-card-head"><small>{l("projectInspector").toUpperCase()}</small><div><h2>{l("videoBrand")}</h2><em>{l("generatedVideo")}</em></div></header><section className="inspector-section"><label className="inspector-field"><span>{l("brandMode")}</span><select value={brand.mode} onChange={e=>set({...brand,mode:e.target.value as typeof brand.mode})}><option value="dark">{l("dark")}</option><option value="light">{l("light")}</option><option value="custom">{l("custom")}</option></select></label>{(["primary","data","success","text","background"] as const).map(key=><label className="inspector-field" key={key}><span>{colorLabels[key]}</span><input type="color" value={brand.colors[key]} onChange={e=>set({...brand,colors:{...brand.colors,[key]:e.target.value}})}/></label>)}<label className="inspector-field"><span>{l("headingFont")}</span><input value={brand.typography.headingFont} onChange={e=>set({...brand,typography:{...brand.typography,headingFont:e.target.value}})}/></label><label className="inspector-field"><span>{l("bodyFont")}</span><input value={brand.typography.bodyFont} onChange={e=>set({...brand,typography:{...brand.typography,bodyFont:e.target.value}})}/></label><label className="inspector-field"><span>{l("captionFont")}</span><input value={brand.typography.captionFont} onChange={e=>set({...brand,typography:{...brand.typography,captionFont:e.target.value}})}/></label><div className="layout-number-grid"><label><span>{l("motionSpeed")}</span><input type="number" min={.1} max={4} step={.1} value={brand.motion.speed} onChange={e=>set({...brand,motion:{...brand.motion,speed:Number(e.target.value)}})}/></label><label><span>{l("effectScale")}</span><input type="number" min={.1} max={5} step={.05} value={brand.motion.scale} onChange={e=>set({...brand,motion:{...brand.motion,scale:Number(e.target.value)}})}/></label></div><label className="inspector-field"><span>{l("intensity")}</span><select value={brand.motion.intensity} onChange={e=>set({...brand,motion:{...brand.motion,intensity:e.target.value as typeof brand.motion.intensity}})}><option value="minimal">{l("minimal")}</option><option value="balanced">{l("balanced")}</option><option value="strong">{l("strong")}</option></select></label></section><section className="inspector-section"><div className="inspector-section-title"><strong>{l("linkedStyles")}</strong><small>{project.linkedStyles.length}</small></div>{project.linkedStyles.length?project.linkedStyles.map(style=><div className="caption-copy" key={style.id}>{style.name}<small> · {style.target}</small></div>):<p>{l("noLinkedStyles")}</p>}</section></div>;
};
