"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import type {Project} from "@/schemas/project";

export const ProjectInspector=({project,onCommand}:{project:Project;onCommand:(command:ProjectCommand,message:string)=>Promise<void>})=>{
  const brand=project.brand;const set=(next:Project["brand"])=>void onCommand({type:"set-brand",brand:next},"Video brand updated");
  return <div className="os-inspector"><header className="inspector-card-head"><small>PROJECT INSPECTOR</small><div><h2>Video Brand</h2><em>Generated Video</em></div></header><section className="inspector-section"><label className="inspector-field"><span>Brand Mode</span><select value={brand.mode} onChange={e=>set({...brand,mode:e.target.value as typeof brand.mode})}><option value="dark">Dark</option><option value="light">Light</option><option value="custom">Custom</option></select></label>{(["primary","data","success","text","background"] as const).map(key=><label className="inspector-field" key={key}><span>{key}</span><input type="color" value={brand.colors[key]} onChange={e=>set({...brand,colors:{...brand.colors,[key]:e.target.value}})}/></label>)}<label className="inspector-field"><span>Heading Font</span><input value={brand.typography.headingFont} onChange={e=>set({...brand,typography:{...brand.typography,headingFont:e.target.value}})}/></label><label className="inspector-field"><span>Body Font</span><input value={brand.typography.bodyFont} onChange={e=>set({...brand,typography:{...brand.typography,bodyFont:e.target.value}})}/></label><label className="inspector-field"><span>Caption Font</span><input value={brand.typography.captionFont} onChange={e=>set({...brand,typography:{...brand.typography,captionFont:e.target.value}})}/></label><div className="layout-number-grid"><label><span>Motion Speed</span><input type="number" min={.1} max={4} step={.1} value={brand.motion.speed} onChange={e=>set({...brand,motion:{...brand.motion,speed:Number(e.target.value)}})}/></label><label><span>Effect Scale</span><input type="number" min={.1} max={5} step={.05} value={brand.motion.scale} onChange={e=>set({...brand,motion:{...brand.motion,scale:Number(e.target.value)}})}/></label></div><label className="inspector-field"><span>Intensity</span><select value={brand.motion.intensity} onChange={e=>set({...brand,motion:{...brand.motion,intensity:e.target.value as typeof brand.motion.intensity}})}><option value="minimal">Minimal</option><option value="balanced">Balanced</option><option value="strong">Strong</option></select></label></section><section className="inspector-section"><div className="inspector-section-title"><strong>Linked Styles</strong><small>{project.linkedStyles.length}</small></div>{project.linkedStyles.length?project.linkedStyles.map(style=><div className="caption-copy" key={style.id}>{style.name}<small> · {style.target}</small></div>):<p>No linked styles yet. Create one from a Motion or Caption Inspector.</p>}</section></div>;
};
