"use client";

import {useMemo,useState} from "react";
import type {ProjectCommand} from "@/lib/project/commands";
import type {Project} from "@/schemas/project";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {useWorkspaceLayout} from "@/components/studio/WorkspaceLayoutProvider";
import {RENDER_REQUEST_EVENT} from "@/components/render/RenderControls";
import {m3Label as label} from "./m3-i18n";
import {buildCanvasChangePreview} from "@/lib/canvas/change-preview";
import {CANVAS_PRESETS,findCanvasPreset} from "@/lib/canvas/aspect";

export const ProjectInspector=({project,onCommand}:{project:Project;onCommand:(command:ProjectCommand,message:string)=>Promise<void>})=>{
  const{locale}=useStudioPreferences();const zh=locale==="zh-CN";const l=(key:Parameters<typeof label>[1])=>label(locale,key);const brand=project.brand;
  const{layout,resetWorkspace}=useWorkspaceLayout();
  const set=(next:Project["brand"])=>void onCommand({type:"set-brand",brand:next},zh?"视频品牌已更新":"Video brand updated");
  const colorLabels={primary:l("primary"),data:l("data"),success:l("success"),text:l("text"),background:l("background")};
  const[canvasDraft,setCanvasDraft]=useState({width:project.canvas.width,height:project.canvas.height});
  const[showCanvasPreview,setShowCanvasPreview]=useState(false);
  const preview=useMemo(()=>buildCanvasChangePreview(project,canvasDraft),[project,canvasDraft]);
  const canvasChanged=canvasDraft.width!==project.canvas.width||canvasDraft.height!==project.canvas.height;
  const currentPreset=findCanvasPreset(project.canvas.width,project.canvas.height);
  const stagePreset=(width:number,height:number)=>{setCanvasDraft({width,height});setShowCanvasPreview(true);};
  const cancelCanvas=()=>{setCanvasDraft({width:project.canvas.width,height:project.canvas.height});setShowCanvasPreview(false);};
  const applyCanvas=async()=>{if(!canvasChanged)return;await onCommand({type:"set-canvas",width:canvasDraft.width,height:canvasDraft.height},zh?"画布已更新":"Canvas updated");setShowCanvasPreview(false);};

  return <div className="os-inspector">
    <header className="inspector-card-head"><small>{l("projectInspector").toUpperCase()}</small><div><h2>{zh?"项目":"Project"}</h2><em>{project.canvas.width}×{project.canvas.height} · {project.canvas.fps} fps</em></div></header>

    <section className="inspector-section" data-inspector-section="canvas">
      <div className="inspector-section-title"><strong>{zh?"画布":"Canvas"}</strong><small>{currentPreset?.label??`${project.canvas.width}×${project.canvas.height}`}</small></div>
      <div className="v21-inspector-canvas-presets">{CANVAS_PRESETS.slice(0,7).map(item=><button key={item.id} className={item.width===canvasDraft.width&&item.height===canvasDraft.height?"active":""} onClick={()=>stagePreset(item.width,item.height)}><strong>{item.label}</strong><small>{item.width}×{item.height}</small></button>)}</div>
      <div className="layout-number-grid"><label><span>{zh?"宽度":"Width"}</span><input type="number" min={16} max={16384} value={canvasDraft.width} onChange={event=>{setCanvasDraft(value=>({...value,width:Math.max(16,Number(event.target.value)||16)}));setShowCanvasPreview(true);}}/></label><label><span>{zh?"高度":"Height"}</span><input type="number" min={16} max={16384} value={canvasDraft.height} onChange={event=>{setCanvasDraft(value=>({...value,height:Math.max(16,Number(event.target.value)||16)}));setShowCanvasPreview(true);}}/></label></div>
      <label className="inspector-field"><span>FPS</span><input value={project.canvas.fps} readOnly/><small>{zh?"项目时间基准与画布尺寸分离。需要不同输出 FPS 时使用 Render / Export Profile。":"Project timebase is separate from Canvas dimensions. Use Render / Export Profile for a different output FPS."}</small></label>
      {showCanvasPreview&&canvasChanged?<div className="v21-canvas-change-preview" role="status"><header><strong>{zh?"画布变更预览":"Canvas Change Preview"}</strong><small>{preview.before.width}×{preview.before.height} · {preview.before.aspectLabel} → {preview.after.width}×{preview.after.height} · {preview.after.aspectLabel}</small></header><div className="v21-canvas-impact-grid"><span>{zh?"字幕":"Captions"}<strong>{preview.affected.captions}</strong></span><span>{zh?"动效":"Motion"}<strong>{preview.affected.motions}</strong></span><span>B-roll<strong>{preview.affected.broll}</strong></span><span>{zh?"视频":"Video"}<strong>{preview.affected.videos}</strong></span></div>{preview.aspectChanged?<p>{zh?"画布比例发生变化。V2.1 将保留现有 Transform；请在 Apply 后检查字幕、动效和 B-roll 构图。":"The aspect ratio will change. V2.1 keeps existing transforms; review captions, motion and B-roll composition after Apply."}</p>:null}<footer><button onClick={cancelCanvas}>{zh?"取消":"Cancel"}</button><button className="v21-primary" onClick={()=>void applyCanvas()}>{zh?"应用画布":"Apply Canvas"}</button></footer></div>:null}
    </section>

    <section className="inspector-section" data-inspector-section="brand"><div className="inspector-section-title"><strong>{l("videoBrand")}</strong><small>{l("generatedVideo")}</small></div><label className="inspector-field"><span>{l("brandMode")}</span><select value={brand.mode} onChange={e=>set({...brand,mode:e.target.value as typeof brand.mode})}><option value="dark">{l("dark")}</option><option value="light">{l("light")}</option><option value="custom">{l("custom")}</option></select></label>{(["primary","data","success","text","background"] as const).map(key=><label className="inspector-field" key={key}><span>{colorLabels[key]}</span><input type="color" value={brand.colors[key]} onChange={e=>set({...brand,colors:{...brand.colors,[key]:e.target.value}})}/></label>)}<label className="inspector-field"><span>{l("headingFont")}</span><input value={brand.typography.headingFont} onChange={e=>set({...brand,typography:{...brand.typography,headingFont:e.target.value}})}/></label><label className="inspector-field"><span>{l("bodyFont")}</span><input value={brand.typography.bodyFont} onChange={e=>set({...brand,typography:{...brand.typography,bodyFont:e.target.value}})}/></label><label className="inspector-field"><span>{l("captionFont")}</span><input value={brand.typography.captionFont} onChange={e=>set({...brand,typography:{...brand.typography,captionFont:e.target.value}})}/></label><div className="layout-number-grid"><label><span>{l("motionSpeed")}</span><input type="number" min={.1} max={4} step={.1} value={brand.motion.speed} onChange={e=>set({...brand,motion:{...brand.motion,speed:Number(e.target.value)}})}/></label><label><span>{l("effectScale")}</span><input type="number" min={.1} max={5} step={.05} value={brand.motion.scale} onChange={e=>set({...brand,motion:{...brand.motion,scale:Number(e.target.value)}})}/></label></div><label className="inspector-field"><span>{l("intensity")}</span><select value={brand.motion.intensity} onChange={e=>set({...brand,motion:{...brand.motion,intensity:e.target.value as typeof brand.motion.intensity}})}><option value="minimal">{l("minimal")}</option><option value="balanced">{l("balanced")}</option><option value="strong">{l("strong")}</option></select></label></section>
    <section className="inspector-section" data-inspector-section="linked"><div className="inspector-section-title"><strong>{l("linkedStyles")}</strong><small>{project.linkedStyles.length}</small></div>{project.linkedStyles.length?project.linkedStyles.map(style=><div className="caption-copy" key={style.id}>{style.name}<small> · {style.target}</small></div>):<p>{l("noLinkedStyles")}</p>}</section>
    <section className="inspector-section" data-inspector-section="workspace"><div className="inspector-section-title"><strong>{zh?"工作区":"Workspace"}</strong><small>{layout.preset.toUpperCase()}</small></div><p className="inspector-help">{zh?"工作区尺寸和折叠状态属于本地偏好，不写入 Project，也不会增加 revision。":"Workspace sizes and collapsed states are local preferences; they do not mutate the Project or revision."}</p><button className="button small" onClick={resetWorkspace}>{zh?"重置当前工作区":"Reset Current Workspace"}</button></section>
    <section className="inspector-section" data-inspector-section="render"><div className="inspector-section-title"><strong>{zh?"渲染 / 导出":"Render / Export"}</strong><small>PROFILE</small></div><p className="inspector-help">{zh?"默认使用 Project Canvas。需要自定义输出尺寸、FPS、质量或音频时打开 Export Profile；不同宽高比会先提示，不进行智能重构。":"Project Canvas is the default. Open Export Profile for custom dimensions, FPS, quality or audio; aspect mismatch warns before render and does not smart-reframe."}</p><button className="v21-primary" onClick={()=>window.dispatchEvent(new CustomEvent(RENDER_REQUEST_EVENT,{detail:{mode:"final"}}))}>{zh?"打开导出设置":"Open Export Profile"}</button></section>
  </div>;
};