"use client";

import type {ProjectCommand} from "@/lib/project/commands";
import type {Project} from "@/schemas/project";

export const SceneInspector=({project,sceneId,onCommand}:{project:Project;sceneId:string;onCommand:(command:ProjectCommand,message:string)=>Promise<void>})=>{
  const scene=project.scenes.find(item=>item.id===sceneId);if(!scene)return null;
  return <div className="os-inspector"><header className="inspector-card-head"><small>SCENE INSPECTOR</small><div><h2>{scene.name}</h2><em>{scene.semanticType}</em></div></header><section className="inspector-section"><label className="inspector-field"><span>Name</span><input value={scene.name} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{name:e.target.value}},"Scene updated")}/></label><label className="inspector-field"><span>Type</span><select value={scene.semanticType} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{semanticType:e.target.value as typeof scene.semanticType}},"Scene updated")}>{["hook","pain","problem","reframe","solution","proof","process","comparison","cta","custom"].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="inspector-field"><span>Summary</span><textarea value={scene.summary??""} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{summary:e.target.value||null}},"Scene updated")}/></label><label className="inspector-field"><span>Visual Intensity</span><select value={scene.visualStrategy?.intensity??"medium"} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{visualStrategy:{intensity:e.target.value as "low"|"medium"|"high",preferredEngines:scene.visualStrategy?.preferredEngines??[]}}},"Scene updated")}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label className="inspector-field"><span>Scene Style</span><select value={scene.styleId??""} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{styleId:e.target.value||null}},"Scene style updated")}><option value="">Inherit Brand</option>{project.linkedStyles.map(style=><option key={style.id} value={style.id}>{style.name}</option>)}</select></label><div className="inspector-meta"><div><span>Range</span><strong>f{scene.startFrame}–f{scene.endFrame}</strong></div><div><span>Segments</span><strong>{project.script.segments.filter(segment=>segment.sceneId===scene.id).length}</strong></div></div></section></div>;
};
