"use client";

import type {KeyboardEvent} from "react";
import type {ProjectCommand} from "@/lib/project/commands";
import type {Project} from "@/schemas/project";
import {useStudioPreferences} from "@/components/i18n/StudioPreferences";
import {m3Label as label,type M3LabelKey} from "./m3-i18n";

const semanticLabels:Record<Project["scenes"][number]["semanticType"],M3LabelKey>={hook:"hook",pain:"pain",problem:"problem",reframe:"reframe",solution:"solution",proof:"proof",process:"process",comparison:"comparison",cta:"cta",custom:"customScene"};
const blurOnEnter=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key==="Enter")event.currentTarget.blur();};

export const SceneInspector=({project,sceneId,onCommand}:{project:Project;sceneId:string;onCommand:(command:ProjectCommand,message:string)=>Promise<void>})=>{
  const{locale}=useStudioPreferences();const l=(key:Parameters<typeof label>[1])=>label(locale,key);const scene=project.scenes.find(item=>item.id===sceneId);if(!scene)return null;const msg=locale==="zh-CN"?"场景已更新":"Scene updated";
  const commitName=(value:string)=>{if(value!==scene.name)void onCommand({type:"update-scene",sceneId:scene.id,patch:{name:value}},msg);};
  const currentSummary=scene.summary??"";
  const commitSummary=(value:string)=>{if(value!==currentSummary)void onCommand({type:"update-scene",sceneId:scene.id,patch:{summary:value||null}},msg);};
  return <div className="os-inspector"><header className="inspector-card-head"><small>{l("sceneInspector").toUpperCase()}</small><div><h2>{scene.name}</h2><em>{l(semanticLabels[scene.semanticType])}</em></div></header><section className="inspector-section"><label className="inspector-field"><span>{l("name")}</span><input defaultValue={scene.name} key={`${scene.id}-name-${scene.name}`} onKeyDown={blurOnEnter} onBlur={e=>commitName(e.target.value)}/></label><label className="inspector-field"><span>{l("type")}</span><select value={scene.semanticType} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{semanticType:e.target.value as typeof scene.semanticType}},msg)}>{(["hook","pain","problem","reframe","solution","proof","process","comparison","cta","custom"] as const).map(value=><option key={value} value={value}>{l(semanticLabels[value])}</option>)}</select></label><label className="inspector-field"><span>{l("summary")}</span><textarea defaultValue={currentSummary} key={`${scene.id}-summary-${currentSummary}`} onBlur={e=>commitSummary(e.target.value)}/></label><label className="inspector-field"><span>{l("visualIntensity")}</span><select value={scene.visualStrategy?.intensity??"medium"} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{visualStrategy:{intensity:e.target.value as "low"|"medium"|"high",preferredEngines:scene.visualStrategy?.preferredEngines??[]}}},msg)}><option value="low">{l("low")}</option><option value="medium">{l("medium")}</option><option value="high">{l("high")}</option></select></label><label className="inspector-field"><span>{l("sceneStyle")}</span><select value={scene.styleId??""} onChange={e=>void onCommand({type:"update-scene",sceneId:scene.id,patch:{styleId:e.target.value||null}},msg)}><option value="">{l("inheritBrand")}</option>{project.linkedStyles.map(style=><option key={style.id} value={style.id}>{style.name}</option>)}</select></label><div className="inspector-meta"><div><span>{l("range")}</span><strong>f{scene.startFrame}–f{scene.endFrame}</strong></div><div><span>{l("segments")}</span><strong>{project.script.segments.filter(segment=>segment.sceneId===scene.id).length}</strong></div></div></section></div>;
};
